<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en"><head>
<script src="STHSMain.js"></script>
<title>CELH - Pro Leaders</title>
<script src="CELH-PLF.js"></script>
<meta name="author" content="Simon Tremblay, sths.simont.info" />
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="Decription" content="Marcus Winston - STHS - Version : 3.1.9.9 - CELH-STHS.db - CELH-STHSCareerStat.db"/>
<link href="STHSMain.css" rel="stylesheet" type="text/css" />
<style>
@media screen and (max-width: 1200px) {
.STHSWarning {display:block;}
.STHSScoring_PlayersTable1 tbody td:nth-last-child(1){display:none;}
.STHSScoring_PlayersTable1 thead th:nth-last-child(1){display:none;}
.STHSScoring_PlayersTable1 tbody td:nth-last-child(2){display:none;}
.STHSScoring_PlayersTable1 thead th:nth-last-child(2){display:none;}
.STHSScoring_PlayersTable1 tbody td:nth-last-child(3){display:none;}
.STHSScoring_PlayersTable1 thead th:nth-last-child(3){display:none;}
}
@media screen and (max-width: 1060px) {
.STHSScoring_PlayersTable1 tbody td:nth-last-child(6){display:none;}
.STHSScoring_PlayersTable1 thead th:nth-last-child(6){display:none;}
.STHSScoring_PlayersTable1 tbody td:nth-last-child(7){display:none;}
.STHSScoring_PlayersTable1 thead th:nth-last-child(7){display:none;}
.STHSScoring_PlayersTable1 tbody td:nth-last-child(8){display:none;}
.STHSScoring_PlayersTable1 thead th:nth-last-child(8){display:none;}
}
@media screen and (max-width: 960px) {
.STHSW10 {display:none;}
.STHSScoring_PlayersTable1 tbody td:nth-child(3){display:none;}
.STHSScoring_PlayersTable1 thead th:nth-child(3){display:none;}
.STHSScoring_PlayersTable1 tbody td:nth-child(4){display:none;}
.STHSScoring_PlayersTable1 thead th:nth-child(4){display:none;}
}
@media screen and (max-width: 890px) {
.STHSW10 {display:none;}
.STHSScoring_PlayersTable1 tbody td:nth-child(13){display:none;}
.STHSScoring_PlayersTable1 thead th:nth-child(13){display:none;}
.STHSScoring_PlayersTable1 tbody td:nth-child(15){display:none;}
.STHSScoring_PlayersTable1 thead th:nth-child(15){display:none;}
.STHSScoring_PlayersTable1 tbody td:nth-child(16){display:none;}
.STHSScoring_PlayersTable1 thead th:nth-child(16){display:none;}
.STHSScoring_GoaliesTable tbody td:nth-last-child(5){display:none;}
.STHSScoring_GoaliesTable thead th:nth-last-child(5){display:none;}
}</style>
<link href="CELH-PLF.css" rel="stylesheet" type="text/css" />
<?php If (file_exists("STHSMain-CSSOverwrite.css") == True){echo "<link href=\"STHSMain-CSSOverwrite.css\" rel=\"stylesheet\" type=\"text/css\" />";}?>
<?php $LeagueName = (string)"";
$DatabaseFile = (string)"CELH-STHS.db";
$LangOverwrite = (boolean)FALSE;
$CareerStatDatabaseFile = (string)"CELH-STHSCareerStat.db";
$lang = (string)"en"; /* The $lang option must be either "en" or "fr" */
if(isset($_GET['Lang'])){$lang  = filter_var($_GET['Lang'], FILTER_SANITIZE_STRING, FILTER_FLAG_STRIP_LOW || FILTER_FLAG_STRIP_HIGH);$LangOverwrite=TRUE;}  /* Allow Users Language Overwrite */
If ($lang == "fr"){include 'LanguageFR.php';}else{include 'LanguageEN.php';}
$db = new SQLite3($DatabaseFile);
$Active = 1; /* Show Webpage Top Menu */
include "Menu.php";?>
<script>$(function(){$("table").basictablesorter()});$(function (){$("table").stickyTableHeaders();});</script>
<table class="basictablesorter STHSScoring_PlayersTable1"><thead><tr><th class="STHSW25">#</th><th class="STHSW200">Player Name</th><th class="STHSW10">F</th><th class="STHSW10">D</th><th class="STHSW25">GP</th><th class="STHSW25">G</th><th class="STHSW25">A</th><th class="STHSW25">P</th><th class="STHSW25">+/-</th><th class="STHSW25">PIM</th><th class="STHSW25">PM5</th><th class="STHSW25">HIT</th><th class="STHSW25">HTT</th><th class="STHSW25">SHT</th><th class="STHSW25">OSB</th><th class="STHSW25">OSM</th><th class="STHSW55">SHT %</th><th class="STHSW25">SB</th><th class="STHSW35">MP</th><th class="STHSW35">AMG</th><th class="STHSW25">PPG</th><th class="STHSW25">PPA</th><th class="STHSW25">PPP</th><th class="STHSW25">PPS</th><th class="STHSW25">PPM</th><th class="STHSW25">PKG</th><th class="STHSW25">PKA</th><th class="STHSW25">PKP</th><th class="STHSW25">PKS</th><th class="STHSW25">PKM</th></tr></thead>
<tr><td>1</td><td><a href="PlayerReport.php?Player=58">Dickie Pecker (R) (BOH)</a></td><td>X</td><td></td><td>10</td><td>3</td><td>11</td><td><b>14</b></td><td>-3</td><td>0</td><td>0</td><td>10</td><td>19</td><td>45</td><td>9</td><td>24</td><td>6.67%</td><td>4</td><td>212</td><td>21.18</td><td>3</td><td>9</td><td>12</td><td>10</td><td>34</td><td>0</td><td>0</td><td>0</td><td>1</td><td>15</td></tr>
<tr><td>2</td><td><a href="PlayerReport.php?Player=55">Walter White (R) (BOH)</a></td><td></td><td>X</td><td>10</td><td>6</td><td>7</td><td><b>13</b></td><td>-1</td><td>10</td><td>0</td><td>28</td><td>18</td><td>47</td><td>16</td><td>13</td><td>12.77%</td><td>13</td><td>283</td><td>28.26</td><td>4</td><td>6</td><td>10</td><td>12</td><td>38</td><td>0</td><td>0</td><td>0</td><td>0</td><td>32</td></tr>
<tr><td>3</td><td><a href="PlayerReport.php?Player=67">Ondrej Ravchitikov (R) (MOR)</a></td><td></td><td>X</td><td>13</td><td>3</td><td>8</td><td><b>11</b></td><td>0</td><td>2</td><td>0</td><td>14</td><td>26</td><td>60</td><td>25</td><td>40</td><td>5.00%</td><td>23</td><td>363</td><td>27.90</td><td>3</td><td>3</td><td>6</td><td>16</td><td>43</td><td>0</td><td>0</td><td>0</td><td>0</td><td>38</td></tr>
<tr><td>4</td><td><a href="PlayerReport.php?Player=16">Dionyz Vyskoc (R) (MOR)</a></td><td>X</td><td></td><td>13</td><td>5</td><td>4</td><td><b>9</b></td><td>4</td><td>6</td><td>0</td><td>12</td><td>18</td><td>16</td><td>5</td><td>9</td><td>31.25%</td><td>4</td><td>232</td><td>17.85</td><td>1</td><td>2</td><td>3</td><td>3</td><td>30</td><td>1</td><td>0</td><td>1</td><td>1</td><td>13</td></tr>
<tr><td>5</td><td><a href="PlayerReport.php?Player=15">DeMaricus Smyth (R) (BOH)</a></td><td>X</td><td></td><td>10</td><td>2</td><td>7</td><td><b>9</b></td><td>-4</td><td>8</td><td>0</td><td>21</td><td>28</td><td>19</td><td>8</td><td>13</td><td>10.53%</td><td>6</td><td>228</td><td>22.79</td><td>2</td><td>7</td><td>9</td><td>4</td><td>34</td><td>0</td><td>0</td><td>0</td><td>0</td><td>29</td></tr>
<tr><td>6</td><td><a href="PlayerReport.php?Player=42">Slappy McDoodle (R) (MOR)</a></td><td>X</td><td></td><td>13</td><td>4</td><td>4</td><td><b>8</b></td><td>3</td><td>8</td><td>0</td><td>20</td><td>21</td><td>35</td><td>10</td><td>19</td><td>11.43%</td><td>5</td><td>299</td><td>22.97</td><td>2</td><td>4</td><td>6</td><td>6</td><td>39</td><td>0</td><td>0</td><td>0</td><td>0</td><td>35</td></tr>
<tr><td>7</td><td><a href="PlayerReport.php?Player=69">Sachimo Zoidberg (R) (MOR)</a></td><td></td><td>X</td><td>13</td><td>2</td><td>6</td><td><b>8</b></td><td>0</td><td>14</td><td>0</td><td>45</td><td>22</td><td>39</td><td>19</td><td>18</td><td>5.13%</td><td>20</td><td>356</td><td>27.36</td><td>0</td><td>3</td><td>3</td><td>7</td><td>43</td><td>0</td><td>0</td><td>0</td><td>0</td><td>33</td></tr>
<tr><td>8</td><td><a href="PlayerReport.php?Player=64">Matej Stransky (R) (BOH)</a></td><td>X</td><td></td><td>10</td><td>5</td><td>2</td><td><b>7</b></td><td>2</td><td>6</td><td>0</td><td>15</td><td>16</td><td>33</td><td>5</td><td>19</td><td>15.15%</td><td>0</td><td>176</td><td>17.60</td><td>3</td><td>1</td><td>4</td><td>4</td><td>27</td><td>0</td><td>0</td><td>0</td><td>0</td><td>14</td></tr>
<tr><td>9</td><td><a href="PlayerReport.php?Player=60">Jakub Trocheck (R) (SBE)</a></td><td></td><td>X</td><td>7</td><td>4</td><td>3</td><td><b>7</b></td><td>-3</td><td>4</td><td>0</td><td>11</td><td>22</td><td>24</td><td>19</td><td>2</td><td>16.67%</td><td>10</td><td>196</td><td>28.02</td><td>4</td><td>2</td><td>6</td><td>5</td><td>21</td><td>0</td><td>0</td><td>0</td><td>0</td><td>23</td></tr>
<tr><td>10</td><td><a href="PlayerReport.php?Player=10">Brady McIntyre (R) (MOR)</a></td><td></td><td>X</td><td>13</td><td>1</td><td>6</td><td><b>7</b></td><td>8</td><td>8</td><td>0</td><td>23</td><td>18</td><td>23</td><td>10</td><td>7</td><td>4.35%</td><td>21</td><td>276</td><td>21.20</td><td>1</td><td>1</td><td>2</td><td>4</td><td>27</td><td>0</td><td>1</td><td>1</td><td>0</td><td>27</td></tr>
<tr><td>11</td><td><a href="PlayerReport.php?Player=33">Piotr Czerkawski (R) (SBE)</a></td><td>X</td><td></td><td>7</td><td>3</td><td>3</td><td><b>6</b></td><td>-4</td><td>8</td><td>0</td><td>15</td><td>11</td><td>24</td><td>6</td><td>17</td><td>12.50%</td><td>5</td><td>182</td><td>26.03</td><td>3</td><td>3</td><td>6</td><td>8</td><td>19</td><td>0</td><td>0</td><td>0</td><td>0</td><td>18</td></tr>
<tr><td>12</td><td><a href="PlayerReport.php?Player=24">Luke Thomason (R) (BOH)</a></td><td>X</td><td></td><td>10</td><td>2</td><td>4</td><td><b>6</b></td><td>-4</td><td>0</td><td>0</td><td>14</td><td>17</td><td>16</td><td>2</td><td>13</td><td>12.50%</td><td>7</td><td>230</td><td>23.03</td><td>2</td><td>4</td><td>6</td><td>3</td><td>33</td><td>0</td><td>0</td><td>0</td><td>1</td><td>33</td></tr>
<tr><td>13</td><td><a href="PlayerReport.php?Player=50">Zivan Zidek (R) (MOR)</a></td><td>X</td><td></td><td>13</td><td>2</td><td>3</td><td><b>5</b></td><td>3</td><td>8</td><td>0</td><td>12</td><td>16</td><td>26</td><td>9</td><td>26</td><td>7.69%</td><td>1</td><td>217</td><td>16.66</td><td>1</td><td>2</td><td>3</td><td>4</td><td>30</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td></tr>
<tr><td>14</td><td><a href="PlayerReport.php?Player=49">Zalleras Szlerchek (R) (SBE)</a></td><td>X</td><td></td><td>7</td><td>0</td><td>5</td><td><b>5</b></td><td>-2</td><td>2</td><td>0</td><td>17</td><td>26</td><td>21</td><td>12</td><td>14</td><td>0.00%</td><td>5</td><td>192</td><td>27.49</td><td>0</td><td>4</td><td>4</td><td>0</td><td>18</td><td>0</td><td>0</td><td>0</td><td>0</td><td>21</td></tr>
<tr><td>15</td><td><a href="PlayerReport.php?Player=73">Vratislav Zbynek (R) (SBE)</a></td><td>X</td><td></td><td>7</td><td>2</td><td>2</td><td><b>4</b></td><td>-1</td><td>2</td><td>0</td><td>16</td><td>7</td><td>26</td><td>12</td><td>11</td><td>7.69%</td><td>4</td><td>134</td><td>19.18</td><td>1</td><td>2</td><td>3</td><td>3</td><td>14</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td></tr>
<tr><td>16</td><td><a href="PlayerReport.php?Player=61">Petr Kolesnikovs (R) (BOH)</a></td><td>X</td><td></td><td>10</td><td>2</td><td>2</td><td><b>4</b></td><td>1</td><td>4</td><td>0</td><td>9</td><td>14</td><td>14</td><td>12</td><td>11</td><td>14.29%</td><td>4</td><td>157</td><td>15.67</td><td>1</td><td>1</td><td>2</td><td>3</td><td>26</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td></tr>
<tr><td>17</td><td><a href="PlayerReport.php?Player=63">Konstantin Voloshin (R) (BOH)</a></td><td>X</td><td></td><td>10</td><td>2</td><td>2</td><td><b>4</b></td><td>2</td><td>2</td><td>0</td><td>5</td><td>8</td><td>21</td><td>6</td><td>10</td><td>9.52%</td><td>4</td><td>121</td><td>12.13</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>1</td><td>11</td></tr>
<tr><td>18</td><td><a href="PlayerReport.php?Player=25">Marian Potoczny (R) (MOR)</a></td><td>X</td><td></td><td>13</td><td>2</td><td>2</td><td><b>4</b></td><td>3</td><td>12</td><td>0</td><td>23</td><td>16</td><td>41</td><td>10</td><td>30</td><td>4.88%</td><td>9</td><td>297</td><td>22.85</td><td>1</td><td>2</td><td>3</td><td>3</td><td>39</td><td>0</td><td>0</td><td>0</td><td>0</td><td>36</td></tr>
<tr><td>19</td><td><a href="PlayerReport.php?Player=2">Alexander Zajac (R) (SBE)</a></td><td>X</td><td></td><td>7</td><td>1</td><td>3</td><td><b>4</b></td><td>-1</td><td>2</td><td>0</td><td>6</td><td>8</td><td>13</td><td>6</td><td>9</td><td>7.69%</td><td>1</td><td>122</td><td>17.37</td><td>1</td><td>3</td><td>4</td><td>2</td><td>19</td><td>0</td><td>0</td><td>0</td><td>1</td><td>11</td></tr>
<tr><td>20</td><td><a href="PlayerReport.php?Player=62">Krysztof Kowalski (R) (SBE)</a></td><td>X</td><td></td><td>7</td><td>1</td><td>3</td><td><b>4</b></td><td>-1</td><td>4</td><td>0</td><td>11</td><td>13</td><td>20</td><td>7</td><td>12</td><td>5.00%</td><td>4</td><td>147</td><td>20.97</td><td>1</td><td>2</td><td>3</td><td>2</td><td>14</td><td>0</td><td>0</td><td>0</td><td>1</td><td>8</td></tr>
<tr><td>21</td><td><a href="PlayerReport.php?Player=46">Travis Jeziak (R) (BOH)</a></td><td>X</td><td></td><td>10</td><td>1</td><td>3</td><td><b>4</b></td><td>1</td><td>4</td><td>0</td><td>22</td><td>13</td><td>9</td><td>4</td><td>9</td><td>11.11%</td><td>0</td><td>157</td><td>15.68</td><td>1</td><td>1</td><td>2</td><td>1</td><td>26</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td></tr>
<tr><td>22</td><td><a href="PlayerReport.php?Player=54">Marek Vyskoc (R) (MOR)</a></td><td>X</td><td></td><td>13</td><td>1</td><td>3</td><td><b>4</b></td><td>3</td><td>8</td><td>0</td><td>15</td><td>11</td><td>27</td><td>7</td><td>19</td><td>3.70%</td><td>7</td><td>216</td><td>16.64</td><td>0</td><td>1</td><td>1</td><td>1</td><td>30</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td></tr>
<tr><td>23</td><td><a href="PlayerReport.php?Player=48">Ty Justice (R) (MOR)</a></td><td></td><td>X</td><td>13</td><td>2</td><td>1</td><td><b>3</b></td><td>8</td><td>2</td><td>0</td><td>22</td><td>12</td><td>20</td><td>8</td><td>3</td><td>10.00%</td><td>24</td><td>275</td><td>21.13</td><td>2</td><td>1</td><td>3</td><td>4</td><td>27</td><td>0</td><td>0</td><td>0</td><td>0</td><td>26</td></tr>
<tr><td>24</td><td><a href="PlayerReport.php?Player=5">Aviad Ratzon (R) (MOR)</a></td><td>X</td><td></td><td>13</td><td>1</td><td>2</td><td><b>3</b></td><td>4</td><td>8</td><td>0</td><td>28</td><td>17</td><td>12</td><td>5</td><td>14</td><td>8.33%</td><td>12</td><td>283</td><td>21.78</td><td>1</td><td>1</td><td>2</td><td>2</td><td>39</td><td>0</td><td>1</td><td>1</td><td>0</td><td>22</td></tr>
<tr><td>25</td><td><a href="PlayerReport.php?Player=31">Petr Mikulak (R) (BOH)</a></td><td>X</td><td></td><td>10</td><td>0</td><td>3</td><td><b>3</b></td><td>2</td><td>2</td><td>0</td><td>11</td><td>5</td><td>11</td><td>6</td><td>12</td><td>0.00%</td><td>0</td><td>114</td><td>11.35</td><td>0</td><td>0</td><td>0</td><td>1</td><td>2</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td></tr>
<tr><td>26</td><td><a href="PlayerReport.php?Player=13">David Kastrba (R) (SBE)</a></td><td>X</td><td></td><td>7</td><td>1</td><td>1</td><td><b>2</b></td><td>0</td><td>0</td><td>0</td><td>12</td><td>4</td><td>13</td><td>8</td><td>6</td><td>7.69%</td><td>3</td><td>84</td><td>12.07</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td></tr>
<tr><td>27</td><td><a href="PlayerReport.php?Player=11">Cameron Urbowicz (R) (BOH)</a></td><td>X</td><td></td><td>10</td><td>1</td><td>1</td><td><b>2</b></td><td>2</td><td>0</td><td>0</td><td>4</td><td>2</td><td>18</td><td>4</td><td>9</td><td>5.56%</td><td>3</td><td>122</td><td>12.19</td><td>0</td><td>0</td><td>0</td><td>0</td><td>3</td><td>0</td><td>0</td><td>0</td><td>1</td><td>9</td></tr>
<tr><td>28</td><td><a href="PlayerReport.php?Player=57">Daniel Garland (R) (MOR)</a></td><td>X</td><td></td><td>13</td><td>1</td><td>1</td><td><b>2</b></td><td>1</td><td>6</td><td>0</td><td>5</td><td>10</td><td>18</td><td>5</td><td>8</td><td>5.56%</td><td>2</td><td>103</td><td>7.92</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td></tr>
<tr><td>29</td><td><a href="PlayerReport.php?Player=26">Matej Elias (R) (SBE)</a></td><td></td><td>X</td><td>7</td><td>0</td><td>2</td><td><b>2</b></td><td>-2</td><td>2</td><td>0</td><td>1</td><td>12</td><td>7</td><td>5</td><td>3</td><td>0.00%</td><td>4</td><td>140</td><td>20.05</td><td>0</td><td>1</td><td>1</td><td>1</td><td>12</td><td>0</td><td>0</td><td>0</td><td>0</td><td>12</td></tr>
<tr><td>30</td><td><a href="PlayerReport.php?Player=32">Pierre-Luc Laflamme (R) (BOH)</a></td><td></td><td>X</td><td>10</td><td>0</td><td>2</td><td><b>2</b></td><td>0</td><td>18</td><td>0</td><td>23</td><td>25</td><td>11</td><td>6</td><td>7</td><td>0.00%</td><td>16</td><td>280</td><td>27.96</td><td>0</td><td>0</td><td>0</td><td>1</td><td>37</td><td>0</td><td>0</td><td>0</td><td>0</td><td>28</td></tr>
<tr><td>31</td><td><a href="PlayerReport.php?Player=56">Cash Savage (R) (KLD)</a></td><td>X</td><td></td><td>4</td><td>1</td><td>0</td><td><b>1</b></td><td>-2</td><td>2</td><td>0</td><td>9</td><td>1</td><td>7</td><td>3</td><td>1</td><td>14.29%</td><td>0</td><td>70</td><td>17.40</td><td>0</td><td>0</td><td>0</td><td>0</td><td>12</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td></tr>
<tr><td>32</td><td><a href="PlayerReport.php?Player=65">Merit Csonka (R) (KLD)</a></td><td>X</td><td></td><td>4</td><td>1</td><td>0</td><td><b>1</b></td><td>1</td><td>4</td><td>0</td><td>9</td><td>10</td><td>25</td><td>5</td><td>12</td><td>4.00%</td><td>1</td><td>99</td><td>24.83</td><td>0</td><td>0</td><td>0</td><td>1</td><td>13</td><td>0</td><td>0</td><td>0</td><td>2</td><td>15</td></tr>
<tr><td>33</td><td><a href="PlayerReport.php?Player=21">Josef Kubinec (R) (SBE)</a></td><td>X</td><td></td><td>7</td><td>1</td><td>0</td><td><b>1</b></td><td>0</td><td>2</td><td>0</td><td>1</td><td>8</td><td>7</td><td>3</td><td>4</td><td>14.29%</td><td>1</td><td>91</td><td>12.95</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>9</td></tr>
<tr><td>34</td><td><a href="PlayerReport.php?Player=38">Samee Iqbal (R) (SBE)</a></td><td></td><td>X</td><td>7</td><td>1</td><td>0</td><td><b>1</b></td><td>-2</td><td>2</td><td>0</td><td>5</td><td>10</td><td>7</td><td>4</td><td>3</td><td>14.29%</td><td>7</td><td>141</td><td>20.21</td><td>1</td><td>0</td><td>1</td><td>1</td><td>12</td><td>0</td><td>0</td><td>0</td><td>0</td><td>12</td></tr>
<tr><td>35</td><td><a href="PlayerReport.php?Player=45">Tokek Takshak (R) (BOH)</a></td><td></td><td>X</td><td>10</td><td>1</td><td>0</td><td><b>1</b></td><td>0</td><td>8</td><td>0</td><td>6</td><td>17</td><td>14</td><td>3</td><td>3</td><td>7.14%</td><td>6</td><td>200</td><td>19.97</td><td>1</td><td>0</td><td>1</td><td>2</td><td>25</td><td>0</td><td>0</td><td>0</td><td>0</td><td>21</td></tr>
<tr><td>36</td><td><a href="PlayerReport.php?Player=29">Nico Gross (R) (MOR)</a></td><td>X</td><td></td><td>13</td><td>1</td><td>0</td><td><b>1</b></td><td>-2</td><td>6</td><td>0</td><td>20</td><td>9</td><td>15</td><td>2</td><td>11</td><td>6.67%</td><td>4</td><td>162</td><td>12.46</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>14</td></tr>
<tr><td>37</td><td><a href="PlayerReport.php?Player=52">Sasha Dangelchek (R) (MOR)</a></td><td>X</td><td></td><td>13</td><td>1</td><td>0</td><td><b>1</b></td><td>1</td><td>0</td><td>0</td><td>6</td><td>4</td><td>4</td><td>1</td><td>2</td><td>25.00%</td><td>5</td><td>102</td><td>7.87</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td></tr>
<tr><td>38</td><td><a href="PlayerReport.php?Player=39">Schnitinfritz Jagr (R) (KLD)</a></td><td>X</td><td></td><td>4</td><td>0</td><td>1</td><td><b>1</b></td><td>1</td><td>2</td><td>0</td><td>4</td><td>2</td><td>13</td><td>6</td><td>3</td><td>0.00%</td><td>2</td><td>87</td><td>21.68</td><td>0</td><td>0</td><td>0</td><td>1</td><td>13</td><td>0</td><td>0</td><td>0</td><td>0</td><td>16</td></tr>
<tr><td>39</td><td><a href="PlayerReport.php?Player=68">Patrik Satan (R) (KLD)</a></td><td>X</td><td></td><td>4</td><td>0</td><td>1</td><td><b>1</b></td><td>-2</td><td>2</td><td>0</td><td>3</td><td>1</td><td>9</td><td>2</td><td>5</td><td>0.00%</td><td>2</td><td>70</td><td>17.41</td><td>0</td><td>0</td><td>0</td><td>1</td><td>12</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td></tr>
<tr><td>40</td><td><a href="PlayerReport.php?Player=12">Charlie Schieck (R) (SBE)</a></td><td></td><td>X</td><td>7</td><td>0</td><td>1</td><td><b>1</b></td><td>-2</td><td>2</td><td>0</td><td>8</td><td>14</td><td>5</td><td>2</td><td>3</td><td>0.00%</td><td>10</td><td>177</td><td>25.34</td><td>0</td><td>1</td><td>1</td><td>1</td><td>21</td><td>0</td><td>0</td><td>0</td><td>0</td><td>22</td></tr>
<tr><td>41</td><td><a href="PlayerReport.php?Player=34">Potato Chips (R) (MOR)</a></td><td>X</td><td></td><td>13</td><td>0</td><td>1</td><td><b>1</b></td><td>1</td><td>0</td><td>0</td><td>4</td><td>4</td><td>18</td><td>3</td><td>8</td><td>0.00%</td><td>4</td><td>108</td><td>8.28</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>3</td></tr>
<tr><td>42</td><td><a href="PlayerReport.php?Player=66">Mikhail Kladno (R) (MOR)</a></td><td>X</td><td></td><td>13</td><td>0</td><td>1</td><td><b>1</b></td><td>-2</td><td>8</td><td>0</td><td>9</td><td>15</td><td>15</td><td>1</td><td>14</td><td>0.00%</td><td>3</td><td>148</td><td>11.40</td><td>0</td><td>0</td><td>0</td><td>0</td><td>1</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td></tr>
</table><table class="basictablesorter STHSScoring_GoaliesTable"><thead><tr><th class="STHSW25">#</th><th class="STHSW200">Goalie Name</th><th class="STHSW25">GP</th><th class="STHSW25">W</th><th class="STHSW25">L</th><th class="STHSW25">OTL</th><th class="STHSW50">PCT</th><th class="STHSW50">GAA</th><th class="STHSW50">MP</th><th class="STHSW25">PIM</th><th class="STHSW25">SO</th><th class="STHSW25">GA</th><th class="STHSW45">SA</th><th class="STHSW45">SAR</th><th class="STHSW25">A</th><th class="STHSW25">EG</th><th class="STHSW50">PS %</th><th class="STHSW25">PSA</th><th class="STHSW25">ST</th><th class="STHSW25">BG</th></tr></thead>
<tr><td>1</td><td><a href="GoalieReport.php?Goalie=1">Chris Partridge (R) (BOH)</a></td><td>10</td><td>6</td><td>2</td><td>2</td><td><b>0.951</b></td><td>1.38</td><td>607</td><td>2</td><td>2</td><td>14</td><td>285</td><td>120</td><td>1</td><td>0</td><td>0.000</td><td>0</td><td>10</td><td>0</td></tr>
<tr><td>2</td><td><a href="GoalieReport.php?Goalie=4">Mike Verminski (R) (SBE)</a></td><td>7</td><td>3</td><td>2</td><td>2</td><td><b>0.936</b></td><td>1.94</td><td>432</td><td>0</td><td>0</td><td>14</td><td>219</td><td>94</td><td>1</td><td>0</td><td>0.000</td><td>0</td><td>7</td><td>0</td></tr>
<tr><td>3</td><td><a href="GoalieReport.php?Goalie=7">Christoffer Bjornsson (R) (MOR)</a></td><td>13</td><td>8</td><td>5</td><td>0</td><td><b>0.926</b></td><td>2.11</td><td>798</td><td>0</td><td>3</td><td>28</td><td>377</td><td>164</td><td>3</td><td>0</td><td>0.000</td><td>0</td><td>13</td><td>0</td></tr>
</table>
<?php include "Footer.php";?>
