<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en"><head>
<script src="STHSMain.js"></script>
<title>CELH - Pro All Players Stats</title>
<script src="CELH.js"></script>
<meta name="author" content="Simon Tremblay, sths.simont.info" />
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="Decription" content="Marcus Winston - STHS - Version : 3.1.9.9 - CELH-STHS.db - CELH-STHSCareerStat.db"/>
<link href="STHSMain.css" rel="stylesheet" type="text/css" />
<style>
@media screen and (max-width: 1200px) {
.STHSWarning {display:block;}
.STHSScoring_PlayersTable1 tbody td:nth-last-child(1){display:none;}
.STHSScoring_PlayersTable1 thead th:nth-last-child(1){display:none;}
.STHSScoring_PlayersTable1 tbody td:nth-last-child(2){display:none;}
.STHSScoring_PlayersTable1 thead th:nth-last-child(2){display:none;}
.STHSScoring_PlayersTable1 tbody td:nth-last-child(3){display:none;}
.STHSScoring_PlayersTable1 thead th:nth-last-child(3){display:none;}
}
@media screen and (max-width: 1060px) {
.STHSScoring_PlayersTable1 tbody td:nth-last-child(6){display:none;}
.STHSScoring_PlayersTable1 thead th:nth-last-child(6){display:none;}
.STHSScoring_PlayersTable1 tbody td:nth-last-child(7){display:none;}
.STHSScoring_PlayersTable1 thead th:nth-last-child(7){display:none;}
.STHSScoring_PlayersTable1 tbody td:nth-last-child(8){display:none;}
.STHSScoring_PlayersTable1 thead th:nth-last-child(8){display:none;}
.STHSScoring_PlayersTable2 tbody td:nth-last-child(1){display:none;}
.STHSScoring_PlayersTable2 thead th:nth-last-child(1){display:none;}
.STHSScoring_PlayersTable2 tbody td:nth-last-child(2){display:none;}
.STHSScoring_PlayersTable2 thead th:nth-last-child(2){display:none;}
.STHSScoring_PlayersTable2 tbody td:nth-last-child(3){display:none;}
.STHSScoring_PlayersTable2 thead th:nth-last-child(3){display:none;}
.STHSScoring_GoaliesTable tbody td:nth-last-child(1){display:none;}
.STHSScoring_GoaliesTable thead th:nth-last-child(1){display:none;}
.STHSScoring_GoaliesTable tbody td:nth-last-child(2){display:none;}
.STHSScoring_GoaliesTable thead th:nth-last-child(2){display:none;}
.STHSScoring_GoaliesTable tbody td:nth-last-child(3){display:none;}
.STHSScoring_GoaliesTable thead th:nth-last-child(3){display:none;}
}
@media screen and (max-width: 960px) {
.STHSW10 {display:none;}
.STHSScoring_PlayersTable1 tbody td:nth-child(2){display:none;}
.STHSScoring_PlayersTable1 thead th:nth-child(2){display:none;}
.STHSScoring_PlayersTable1 tbody td:nth-child(3){display:none;}
.STHSScoring_PlayersTable1 thead th:nth-child(3){display:none;}
.STHSScoring_PlayersTable2 tbody td:nth-child(2){display:none;}
.STHSScoring_PlayersTable2 thead th:nth-child(2){display:none;}
.STHSScoring_PlayersTable2 tbody td:nth-child(3){display:none;}
.STHSScoring_PlayersTable2 thead th:nth-child(3){display:none;}
}
@media screen and (max-width: 890px) {
.STHSW10 {display:none;}
.STHSScoring_PlayersTable1 tbody td:nth-child(12){display:none;}
.STHSScoring_PlayersTable1 thead th:nth-child(12){display:none;}
.STHSScoring_PlayersTable1 tbody td:nth-child(14){display:none;}
.STHSScoring_PlayersTable1 thead th:nth-child(14){display:none;}
.STHSScoring_PlayersTable1 tbody td:nth-child(15){display:none;}
.STHSScoring_PlayersTable1 thead th:nth-child(15){display:none;}
.STHSScoring_GoaliesTable tbody td:nth-last-child(8){display:none;}
.STHSScoring_GoaliesTable thead th:nth-last-child(8){display:none;}
}</style>
<link href="CELH.css" rel="stylesheet" type="text/css" />
<?php If (file_exists("STHSMain-CSSOverwrite.css") == True){echo "<link href=\"STHSMain-CSSOverwrite.css\" rel=\"stylesheet\" type=\"text/css\" />";}?>
</head><body>
<?php $LeagueName = (string)"";
$DatabaseFile = (string)"CELH-STHS.db";
$LangOverwrite = (boolean)FALSE;
$CareerStatDatabaseFile = (string)"CELH-STHSCareerStat.db";
$lang = (string)"en"; /* The $lang option must be either "en" or "fr" */
if(isset($_GET['Lang'])){$lang  = filter_var($_GET['Lang'], FILTER_SANITIZE_STRING, FILTER_FLAG_STRIP_LOW || FILTER_FLAG_STRIP_HIGH);$LangOverwrite=TRUE;}  /* Allow Users Language Overwrite */
If ($lang == "fr"){include 'LanguageFR.php';}else{include 'LanguageEN.php';}
$db = new SQLite3($DatabaseFile);
$Active = 1; /* Show Webpage Top Menu */
include "Menu.php";?>
<script>$(function(){$("table").basictablesorter()});</script>
<h1 class="ProTotalPlayerStat_Player1">Pro Players Stats #1</h1>
<table class="basictablesorter STHSScoring_PlayersTable1"><thead><tr><th class="STHSW200">Player Name</th><th class="STHSW10">F</th><th class="STHSW10">D</th><th class="STHSW25">GP</th><th class="STHSW25">G</th><th class="STHSW25">A</th><th class="STHSW25">P</th><th class="STHSW25">+/-</th><th class="STHSW25">PIM</th><th class="STHSW25">PM5</th><th class="STHSW25">HIT</th><th class="STHSW25">HTT</th><th class="STHSW25">SHT</th><th class="STHSW25">OSB</th><th class="STHSW25">OSM</th><th class="STHSW55">SHT %</th><th class="STHSW25">SB</th><th class="STHSW35">MP</th><th class="STHSW35">AMG</th><th class="STHSW25">PPG</th><th class="STHSW25">PPA</th><th class="STHSW25">PPP</th><th class="STHSW25">PPS</th><th class="STHSW25">PPM</th><th class="STHSW25">PKG</th><th class="STHSW25">PKA</th><th class="STHSW25">PKP</th><th class="STHSW25">PKS</th><th class="STHSW25">PKM</th></tr></thead>
<tr><td><a href="PlayerReport.php?Player=67">Ondrej Ravchitikov (R) (MOR)</a></td><td></td><td>X</td><td>30</td><td>13</td><td>28</td><td><b>41</b></td><td>2</td><td>6</td><td>0</td><td>29</td><td>67</td><td>161</td><td>60</td><td>81</td><td>8.07%</td><td>33</td><td>843</td><td>28.11</td><td>9</td><td>15</td><td>24</td><td>21</td><td>95</td><td>1</td><td>1</td><td>2</td><td>6</td><td>96</td></tr>
<tr><td><a href="PlayerReport.php?Player=55">Walter White (R) (BOH)</a></td><td></td><td>X</td><td>30</td><td>9</td><td>27</td><td><b>36</b></td><td>4</td><td>22</td><td>0</td><td>89</td><td>60</td><td>123</td><td>54</td><td>68</td><td>7.32%</td><td>44</td><td>852</td><td>28.41</td><td>9</td><td>13</td><td>22</td><td>24</td><td>88</td><td>0</td><td>0</td><td>0</td><td>4</td><td>97</td></tr>
<tr><td><a href="PlayerReport.php?Player=25">Marian Potoczny (R) (MOR)</a></td><td>X</td><td></td><td>30</td><td>14</td><td>16</td><td><b>30</b></td><td>7</td><td>24</td><td>0</td><td>40</td><td>34</td><td>113</td><td>30</td><td>77</td><td>12.39%</td><td>13</td><td>684</td><td>22.79</td><td>5</td><td>11</td><td>16</td><td>15</td><td>88</td><td>0</td><td>1</td><td>1</td><td>0</td><td>84</td></tr>
<tr><td><a href="PlayerReport.php?Player=58">Dickie Pecker (R) (BOH)</a></td><td>X</td><td></td><td>30</td><td>14</td><td>14</td><td><b>28</b></td><td>2</td><td>4</td><td>0</td><td>18</td><td>42</td><td>150</td><td>44</td><td>75</td><td>9.33%</td><td>13</td><td>635</td><td>21.18</td><td>7</td><td>10</td><td>17</td><td>19</td><td>77</td><td>1</td><td>0</td><td>1</td><td>4</td><td>39</td></tr>
<tr><td><a href="PlayerReport.php?Player=69">Sachimo Zoidberg (R) (MOR)</a></td><td></td><td>X</td><td>30</td><td>7</td><td>18</td><td><b>25</b></td><td>-1</td><td>24</td><td>0</td><td>85</td><td>49</td><td>85</td><td>46</td><td>37</td><td>8.24%</td><td>39</td><td>831</td><td>27.71</td><td>5</td><td>10</td><td>15</td><td>18</td><td>95</td><td>1</td><td>0</td><td>1</td><td>2</td><td>91</td></tr>
<tr><td><a href="PlayerReport.php?Player=33">Piotr Czerkawski (R) (SBE)</a></td><td>X</td><td></td><td>30</td><td>10</td><td>14</td><td><b>24</b></td><td>3</td><td>20</td><td>0</td><td>64</td><td>60</td><td>98</td><td>30</td><td>45</td><td>10.20%</td><td>11</td><td>760</td><td>25.33</td><td>5</td><td>10</td><td>15</td><td>15</td><td>94</td><td>0</td><td>0</td><td>0</td><td>0</td><td>77</td></tr>
<tr><td><a href="PlayerReport.php?Player=42">Slappy McDoodle (R) (MOR)</a></td><td>X</td><td></td><td>30</td><td>7</td><td>16</td><td><b>23</b></td><td>6</td><td>16</td><td>0</td><td>62</td><td>54</td><td>98</td><td>23</td><td>51</td><td>7.14%</td><td>19</td><td>690</td><td>22.99</td><td>4</td><td>8</td><td>12</td><td>8</td><td>88</td><td>0</td><td>0</td><td>0</td><td>1</td><td>91</td></tr>
<tr><td><a href="PlayerReport.php?Player=49">Zalleras Szlerchek (R) (SBE)</a></td><td>X</td><td></td><td>30</td><td>5</td><td>18</td><td><b>23</b></td><td>-2</td><td>10</td><td>0</td><td>64</td><td>86</td><td>93</td><td>23</td><td>65</td><td>5.38%</td><td>14</td><td>792</td><td>26.39</td><td>4</td><td>10</td><td>14</td><td>10</td><td>94</td><td>0</td><td>0</td><td>0</td><td>2</td><td>79</td></tr>
<tr><td><a href="PlayerReport.php?Player=65">Merit Csonka (R) (KLD)</a></td><td>X</td><td></td><td>30</td><td>13</td><td>9</td><td><b>22</b></td><td>-5</td><td>10</td><td>0</td><td>92</td><td>56</td><td>142</td><td>36</td><td>96</td><td>9.15%</td><td>23</td><td>771</td><td>25.70</td><td>8</td><td>5</td><td>13</td><td>21</td><td>88</td><td>0</td><td>0</td><td>0</td><td>2</td><td>80</td></tr>
<tr><td><a href="PlayerReport.php?Player=15">DeMaricus Smyth (R) (BOH)</a></td><td>X</td><td></td><td>30</td><td>3</td><td>17</td><td><b>20</b></td><td>2</td><td>26</td><td>0</td><td>68</td><td>83</td><td>59</td><td>18</td><td>29</td><td>5.08%</td><td>16</td><td>699</td><td>23.30</td><td>1</td><td>11</td><td>12</td><td>2</td><td>78</td><td>0</td><td>0</td><td>0</td><td>0</td><td>91</td></tr>
<tr><td><a href="PlayerReport.php?Player=39">Schnitinfritz Jagr (R) (KLD)</a></td><td>X</td><td></td><td>30</td><td>3</td><td>16</td><td><b>19</b></td><td>-4</td><td>24</td><td>0</td><td>38</td><td>61</td><td>52</td><td>20</td><td>39</td><td>5.77%</td><td>23</td><td>649</td><td>21.63</td><td>1</td><td>12</td><td>13</td><td>4</td><td>88</td><td>0</td><td>0</td><td>0</td><td>0</td><td>78</td></tr>
<tr><td><a href="PlayerReport.php?Player=62">Krysztof Kowalski (R) (SBE)</a></td><td>X</td><td></td><td>30</td><td>8</td><td>10</td><td><b>18</b></td><td>-3</td><td>11</td><td>5</td><td>47</td><td>64</td><td>75</td><td>29</td><td>40</td><td>10.67%</td><td>13</td><td>617</td><td>20.57</td><td>4</td><td>7</td><td>11</td><td>14</td><td>77</td><td>1</td><td>0</td><td>1</td><td>5</td><td>42</td></tr>
<tr><td><a href="PlayerReport.php?Player=5">Aviad Ratzon (R) (MOR)</a></td><td>X</td><td></td><td>30</td><td>6</td><td>10</td><td><b>16</b></td><td>6</td><td>10</td><td>0</td><td>57</td><td>39</td><td>43</td><td>21</td><td>19</td><td>13.95%</td><td>10</td><td>651</td><td>21.71</td><td>2</td><td>5</td><td>7</td><td>7</td><td>87</td><td>0</td><td>0</td><td>0</td><td>0</td><td>59</td></tr>
<tr><td><a href="PlayerReport.php?Player=68">Patrik Satan (R) (KLD)</a></td><td>X</td><td></td><td>30</td><td>8</td><td>7</td><td><b>15</b></td><td>-1</td><td>18</td><td>0</td><td>42</td><td>34</td><td>83</td><td>29</td><td>48</td><td>9.64%</td><td>8</td><td>531</td><td>17.69</td><td>5</td><td>2</td><td>7</td><td>11</td><td>67</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td></tr>
<tr><td><a href="PlayerReport.php?Player=73">Vratislav Zbynek (R) (SBE)</a></td><td>X</td><td></td><td>30</td><td>5</td><td>10</td><td><b>15</b></td><td>-6</td><td>18</td><td>0</td><td>46</td><td>49</td><td>109</td><td>29</td><td>68</td><td>4.59%</td><td>12</td><td>564</td><td>18.80</td><td>4</td><td>6</td><td>10</td><td>10</td><td>78</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td></tr>
<tr><td><a href="PlayerReport.php?Player=50">Zivan Zidek (R) (MOR)</a></td><td>X</td><td></td><td>30</td><td>6</td><td>8</td><td><b>14</b></td><td>-1</td><td>12</td><td>0</td><td>22</td><td>40</td><td>54</td><td>19</td><td>48</td><td>11.11%</td><td>8</td><td>479</td><td>15.97</td><td>5</td><td>5</td><td>10</td><td>9</td><td>63</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td></tr>
<tr><td><a href="PlayerReport.php?Player=24">Luke Thomason (R) (BOH)</a></td><td>X</td><td></td><td>30</td><td>5</td><td>9</td><td><b>14</b></td><td>1</td><td>10</td><td>0</td><td>49</td><td>38</td><td>49</td><td>22</td><td>39</td><td>10.20%</td><td>17</td><td>697</td><td>23.24</td><td>2</td><td>5</td><td>7</td><td>5</td><td>77</td><td>0</td><td>0</td><td>0</td><td>1</td><td>93</td></tr>
<tr><td><a href="PlayerReport.php?Player=72">Tomas Pylon (R) (KLD)</a></td><td></td><td>X</td><td>30</td><td>1</td><td>13</td><td><b>14</b></td><td>-3</td><td>16</td><td>0</td><td>48</td><td>54</td><td>68</td><td>26</td><td>33</td><td>1.47%</td><td>41</td><td>879</td><td>29.29</td><td>1</td><td>6</td><td>7</td><td>6</td><td>95</td><td>0</td><td>0</td><td>0</td><td>2</td><td>81</td></tr>
<tr><td><a href="PlayerReport.php?Player=60">Jakub Trocheck (R) (SBE)</a></td><td></td><td>X</td><td>30</td><td>7</td><td>6</td><td><b>13</b></td><td>1</td><td>28</td><td>0</td><td>22</td><td>68</td><td>79</td><td>36</td><td>25</td><td>8.86%</td><td>58</td><td>831</td><td>27.70</td><td>5</td><td>4</td><td>9</td><td>15</td><td>105</td><td>0</td><td>0</td><td>0</td><td>3</td><td>78</td></tr>
<tr><td><a href="PlayerReport.php?Player=56">Cash Savage (R) (KLD)</a></td><td>X</td><td></td><td>30</td><td>6</td><td>7</td><td><b>13</b></td><td>-1</td><td>10</td><td>0</td><td>61</td><td>35</td><td>65</td><td>25</td><td>47</td><td>9.23%</td><td>10</td><td>531</td><td>17.71</td><td>2</td><td>3</td><td>5</td><td>6</td><td>66</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td></tr>
<tr><td><a href="PlayerReport.php?Player=64">Matej Stransky (R) (BOH)</a></td><td>X</td><td></td><td>30</td><td>5</td><td>6</td><td><b>11</b></td><td>5</td><td>26</td><td>0</td><td>57</td><td>35</td><td>103</td><td>30</td><td>67</td><td>4.85%</td><td>5</td><td>522</td><td>17.41</td><td>1</td><td>2</td><td>3</td><td>4</td><td>63</td><td>0</td><td>1</td><td>1</td><td>7</td><td>35</td></tr>
<tr><td><a href="PlayerReport.php?Player=53">Jakub Novak (R) (SBE)</a></td><td>X</td><td></td><td>30</td><td>6</td><td>4</td><td><b>10</b></td><td>-6</td><td>20</td><td>0</td><td>37</td><td>38</td><td>19</td><td>8</td><td>20</td><td>31.58%</td><td>19</td><td>563</td><td>18.78</td><td>3</td><td>3</td><td>6</td><td>4</td><td>78</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td></tr>
<tr><td><a href="PlayerReport.php?Player=2">Alexander Zajac (R) (SBE)</a></td><td>X</td><td></td><td>30</td><td>4</td><td>6</td><td><b>10</b></td><td>5</td><td>10</td><td>0</td><td>35</td><td>28</td><td>64</td><td>14</td><td>35</td><td>6.25%</td><td>7</td><td>523</td><td>17.43</td><td>2</td><td>2</td><td>4</td><td>13</td><td>94</td><td>0</td><td>1</td><td>1</td><td>4</td><td>50</td></tr>
<tr><td><a href="PlayerReport.php?Player=32">Pierre-Luc Laflamme (R) (BOH)</a></td><td></td><td>X</td><td>30</td><td>4</td><td>5</td><td><b>9</b></td><td>4</td><td>24</td><td>0</td><td>59</td><td>51</td><td>46</td><td>9</td><td>17</td><td>8.70%</td><td>46</td><td>844</td><td>28.12</td><td>4</td><td>3</td><td>7</td><td>5</td><td>88</td><td>0</td><td>0</td><td>0</td><td>2</td><td>95</td></tr>
<tr><td><a href="PlayerReport.php?Player=27">Michael Scarn (R) (KLD)</a></td><td>X</td><td></td><td>30</td><td>3</td><td>6</td><td><b>9</b></td><td>-1</td><td>4</td><td>0</td><td>46</td><td>49</td><td>49</td><td>13</td><td>23</td><td>6.12%</td><td>9</td><td>568</td><td>18.92</td><td>1</td><td>2</td><td>3</td><td>6</td><td>67</td><td>0</td><td>0</td><td>0</td><td>2</td><td>30</td></tr>
<tr><td><a href="PlayerReport.php?Player=7">Barret McCarthy (R) (KLD)</a></td><td></td><td>X</td><td>30</td><td>2</td><td>6</td><td><b>8</b></td><td>1</td><td>16</td><td>0</td><td>55</td><td>44</td><td>29</td><td>17</td><td>20</td><td>6.90%</td><td>47</td><td>783</td><td>26.10</td><td>1</td><td>3</td><td>4</td><td>1</td><td>61</td><td>0</td><td>0</td><td>0</td><td>1</td><td>51</td></tr>
<tr><td><a href="PlayerReport.php?Player=61">Petr Kolesnikovs (R) (BOH)</a></td><td>X</td><td></td><td>30</td><td>2</td><td>6</td><td><b>8</b></td><td>3</td><td>16</td><td>0</td><td>29</td><td>32</td><td>68</td><td>19</td><td>25</td><td>2.94%</td><td>9</td><td>477</td><td>15.91</td><td>0</td><td>3</td><td>3</td><td>5</td><td>63</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td></tr>
<tr><td><a href="PlayerReport.php?Player=46">Travis Jeziak (R) (BOH)</a></td><td>X</td><td></td><td>30</td><td>5</td><td>2</td><td><b>7</b></td><td>4</td><td>8</td><td>0</td><td>43</td><td>52</td><td>23</td><td>1</td><td>13</td><td>21.74%</td><td>9</td><td>479</td><td>15.96</td><td>2</td><td>1</td><td>3</td><td>2</td><td>63</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td></tr>
<tr><td><a href="PlayerReport.php?Player=12">Charlie Schieck (R) (SBE)</a></td><td></td><td>X</td><td>30</td><td>3</td><td>4</td><td><b>7</b></td><td>1</td><td>4</td><td>0</td><td>48</td><td>45</td><td>35</td><td>6</td><td>14</td><td>8.57%</td><td>32</td><td>737</td><td>24.58</td><td>3</td><td>2</td><td>5</td><td>10</td><td>105</td><td>0</td><td>0</td><td>0</td><td>0</td><td>91</td></tr>
<tr><td><a href="PlayerReport.php?Player=54">Marek Vyskoc (R) (MOR)</a></td><td>X</td><td></td><td>30</td><td>2</td><td>5</td><td><b>7</b></td><td>-3</td><td>8</td><td>0</td><td>33</td><td>32</td><td>79</td><td>17</td><td>37</td><td>2.53%</td><td>7</td><td>488</td><td>16.27</td><td>0</td><td>4</td><td>4</td><td>5</td><td>64</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td></tr>
<tr><td><a href="PlayerReport.php?Player=10">Brady McIntyre (R) (MOR)</a></td><td></td><td>X</td><td>30</td><td>1</td><td>6</td><td><b>7</b></td><td>-1</td><td>30</td><td>0</td><td>45</td><td>36</td><td>70</td><td>23</td><td>27</td><td>1.43%</td><td>43</td><td>612</td><td>20.41</td><td>1</td><td>3</td><td>4</td><td>2</td><td>60</td><td>0</td><td>0</td><td>0</td><td>3</td><td>60</td></tr>
<tr><td><a href="PlayerReport.php?Player=1">Alex Winters (R) (KLD)</a></td><td>X</td><td></td><td>30</td><td>4</td><td>2</td><td><b>6</b></td><td>-4</td><td>18</td><td>0</td><td>42</td><td>26</td><td>31</td><td>7</td><td>23</td><td>12.90%</td><td>15</td><td>613</td><td>20.45</td><td>1</td><td>2</td><td>3</td><td>4</td><td>87</td><td>0</td><td>0</td><td>0</td><td>3</td><td>50</td></tr>
<tr><td><a href="PlayerReport.php?Player=16">Dionyz Vyskoc (R) (MOR)</a></td><td>X</td><td></td><td>30</td><td>3</td><td>3</td><td><b>6</b></td><td>1</td><td>7</td><td>5</td><td>37</td><td>40</td><td>42</td><td>10</td><td>27</td><td>7.14%</td><td>13</td><td>532</td><td>17.74</td><td>1</td><td>2</td><td>3</td><td>2</td><td>64</td><td>0</td><td>0</td><td>0</td><td>1</td><td>36</td></tr>
<tr><td><a href="PlayerReport.php?Player=38">Samee Iqbal (R) (SBE)</a></td><td></td><td>X</td><td>30</td><td>1</td><td>5</td><td><b>6</b></td><td>-3</td><td>18</td><td>0</td><td>18</td><td>41</td><td>19</td><td>12</td><td>20</td><td>5.26%</td><td>24</td><td>598</td><td>19.93</td><td>0</td><td>2</td><td>2</td><td>3</td><td>71</td><td>0</td><td>0</td><td>0</td><td>2</td><td>51</td></tr>
<tr><td><a href="PlayerReport.php?Player=41">Shouta Aizawa (R) (KLD)</a></td><td>X</td><td></td><td>30</td><td>1</td><td>5</td><td><b>6</b></td><td>1</td><td>10</td><td>0</td><td>44</td><td>36</td><td>47</td><td>30</td><td>39</td><td>2.13%</td><td>12</td><td>401</td><td>13.37</td><td>0</td><td>0</td><td>0</td><td>0</td><td>5</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td></tr>
<tr><td><a href="PlayerReport.php?Player=63">Konstantin Voloshin (R) (BOH)</a></td><td>X</td><td></td><td>30</td><td>2</td><td>3</td><td><b>5</b></td><td>-1</td><td>4</td><td>0</td><td>18</td><td>31</td><td>63</td><td>17</td><td>48</td><td>3.17%</td><td>6</td><td>365</td><td>12.16</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>1</td><td>39</td></tr>
<tr><td><a href="PlayerReport.php?Player=59">Grayson St. Raegan (R) (KLD)</a></td><td>X</td><td></td><td>30</td><td>4</td><td>0</td><td><b>4</b></td><td>2</td><td>4</td><td>0</td><td>35</td><td>26</td><td>65</td><td>20</td><td>25</td><td>6.15%</td><td>4</td><td>416</td><td>13.88</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>1</td><td>35</td></tr>
<tr><td><a href="PlayerReport.php?Player=31">Petr Mikulak (R) (BOH)</a></td><td>X</td><td></td><td>30</td><td>2</td><td>2</td><td><b>4</b></td><td>-2</td><td>10</td><td>0</td><td>19</td><td>20</td><td>42</td><td>13</td><td>23</td><td>4.76%</td><td>4</td><td>333</td><td>11.10</td><td>0</td><td>0</td><td>0</td><td>0</td><td>5</td><td>0</td><td>0</td><td>0</td><td>0</td><td>1</td></tr>
<tr><td><a href="PlayerReport.php?Player=48">Ty Justice (R) (MOR)</a></td><td></td><td>X</td><td>30</td><td>2</td><td>2</td><td><b>4</b></td><td>-2</td><td>22</td><td>0</td><td>45</td><td>44</td><td>34</td><td>6</td><td>10</td><td>5.88%</td><td>31</td><td>609</td><td>20.32</td><td>2</td><td>1</td><td>3</td><td>3</td><td>60</td><td>0</td><td>0</td><td>0</td><td>2</td><td>63</td></tr>
<tr><td><a href="PlayerReport.php?Player=45">Tokek Takshak (R) (BOH)</a></td><td></td><td>X</td><td>30</td><td>1</td><td>3</td><td><b>4</b></td><td>3</td><td>25</td><td>5</td><td>20</td><td>40</td><td>43</td><td>10</td><td>12</td><td>2.33%</td><td>30</td><td>603</td><td>20.10</td><td>0</td><td>0</td><td>0</td><td>1</td><td>55</td><td>0</td><td>0</td><td>0</td><td>2</td><td>60</td></tr>
<tr><td><a href="PlayerReport.php?Player=47">Troy McClure III (R) (KLD)</a></td><td></td><td>X</td><td>30</td><td>1</td><td>3</td><td><b>4</b></td><td>-4</td><td>18</td><td>0</td><td>73</td><td>48</td><td>37</td><td>8</td><td>12</td><td>2.70%</td><td>34</td><td>760</td><td>25.35</td><td>1</td><td>1</td><td>2</td><td>5</td><td>96</td><td>0</td><td>0</td><td>0</td><td>1</td><td>84</td></tr>
<tr><td><a href="PlayerReport.php?Player=20">Jan Zacha (R) (BOH)</a></td><td>X</td><td></td><td>30</td><td>2</td><td>1</td><td><b>3</b></td><td>0</td><td>4</td><td>0</td><td>15</td><td>25</td><td>47</td><td>8</td><td>30</td><td>4.26%</td><td>5</td><td>260</td><td>8.66</td><td>0</td><td>0</td><td>0</td><td>1</td><td>3</td><td>0</td><td>0</td><td>0</td><td>1</td><td>19</td></tr>
<tr><td><a href="PlayerReport.php?Player=21">Josef Kubinec (R) (SBE)</a></td><td>X</td><td></td><td>30</td><td>2</td><td>1</td><td><b>3</b></td><td>-1</td><td>4</td><td>0</td><td>23</td><td>32</td><td>25</td><td>6</td><td>12</td><td>8.00%</td><td>4</td><td>380</td><td>12.67</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>1</td><td>36</td></tr>
<tr><td><a href="PlayerReport.php?Player=29">Nico Gross (R) (MOR)</a></td><td>X</td><td></td><td>30</td><td>2</td><td>1</td><td><b>3</b></td><td>-2</td><td>14</td><td>0</td><td>44</td><td>19</td><td>30</td><td>11</td><td>19</td><td>6.67%</td><td>4</td><td>373</td><td>12.45</td><td>0</td><td>0</td><td>0</td><td>0</td><td>4</td><td>0</td><td>1</td><td>1</td><td>0</td><td>38</td></tr>
<tr><td><a href="PlayerReport.php?Player=35">Przemyslaw Brzeszczyczkiewicz (R) (SBE)</a></td><td>X</td><td></td><td>30</td><td>2</td><td>1</td><td><b>3</b></td><td>5</td><td>6</td><td>0</td><td>23</td><td>35</td><td>27</td><td>8</td><td>15</td><td>7.41%</td><td>5</td><td>273</td><td>9.10</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td></tr>
<tr><td><a href="PlayerReport.php?Player=13">David Kastrba (R) (SBE)</a></td><td>X</td><td></td><td>30</td><td>1</td><td>2</td><td><b>3</b></td><td>-1</td><td>8</td><td>0</td><td>54</td><td>37</td><td>38</td><td>14</td><td>32</td><td>2.63%</td><td>11</td><td>355</td><td>11.83</td><td>0</td><td>0</td><td>0</td><td>0</td><td>4</td><td>0</td><td>0</td><td>0</td><td>0</td><td>2</td></tr>
<tr><td><a href="PlayerReport.php?Player=40">Sean Stevenson Jr. (R) (BOH)</a></td><td></td><td>X</td><td>30</td><td>1</td><td>2</td><td><b>3</b></td><td>3</td><td>14</td><td>0</td><td>41</td><td>38</td><td>25</td><td>8</td><td>23</td><td>4.00%</td><td>31</td><td>604</td><td>20.15</td><td>1</td><td>0</td><td>1</td><td>1</td><td>55</td><td>0</td><td>0</td><td>0</td><td>1</td><td>64</td></tr>
<tr><td><a href="PlayerReport.php?Player=36">Radovan Hudec (R) (KLD)</a></td><td>X</td><td></td><td>30</td><td>1</td><td>1</td><td><b>2</b></td><td>-1</td><td>4</td><td>0</td><td>8</td><td>8</td><td>16</td><td>2</td><td>10</td><td>6.25%</td><td>6</td><td>185</td><td>6.17</td><td>0</td><td>0</td><td>0</td><td>0</td><td>1</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td></tr>
<tr><td><a href="PlayerReport.php?Player=37">Ravyn Tedisko (R) (KLD)</a></td><td>X</td><td></td><td>30</td><td>1</td><td>1</td><td><b>2</b></td><td>-1</td><td>2</td><td>0</td><td>20</td><td>12</td><td>11</td><td>3</td><td>4</td><td>9.09%</td><td>7</td><td>183</td><td>6.10</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td></tr>
<tr><td><a href="PlayerReport.php?Player=6">Barak Obrana (R) (MOR)</a></td><td></td><td>X</td><td>30</td><td>0</td><td>2</td><td><b>2</b></td><td>2</td><td>18</td><td>0</td><td>30</td><td>14</td><td>11</td><td>4</td><td>6</td><td>0.00%</td><td>15</td><td>395</td><td>13.16</td><td>0</td><td>0</td><td>0</td><td>0</td><td>1</td><td>0</td><td>0</td><td>0</td><td>0</td><td>27</td></tr>
<tr><td><a href="PlayerReport.php?Player=14">David Vent (R) (BOH)</a></td><td></td><td>X</td><td>30</td><td>0</td><td>2</td><td><b>2</b></td><td>-2</td><td>8</td><td>0</td><td>20</td><td>22</td><td>17</td><td>7</td><td>9</td><td>0.00%</td><td>14</td><td>361</td><td>12.02</td><td>0</td><td>0</td><td>0</td><td>0</td><td>2</td><td>0</td><td>0</td><td>0</td><td>0</td><td>3</td></tr>
<tr><td><a href="PlayerReport.php?Player=23">Kornel Kasparek (R) (KLD)</a></td><td></td><td>X</td><td>30</td><td>0</td><td>2</td><td><b>2</b></td><td>-3</td><td>16</td><td>0</td><td>51</td><td>21</td><td>11</td><td>10</td><td>7</td><td>0.00%</td><td>18</td><td>356</td><td>11.85</td><td>0</td><td>0</td><td>0</td><td>0</td><td>2</td><td>0</td><td>0</td><td>0</td><td>0</td><td>2</td></tr>
<tr><td><a href="PlayerReport.php?Player=66">Mikhail Kladno (R) (MOR)</a></td><td>X</td><td></td><td>30</td><td>0</td><td>2</td><td><b>2</b></td><td>-2</td><td>10</td><td>0</td><td>30</td><td>26</td><td>25</td><td>14</td><td>25</td><td>0.00%</td><td>10</td><td>334</td><td>11.14</td><td>0</td><td>0</td><td>0</td><td>0</td><td>4</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td></tr>
<tr><td><a href="PlayerReport.php?Player=4">Aron Hernadivic (R) (SBE)</a></td><td>X</td><td></td><td>30</td><td>1</td><td>0</td><td><b>1</b></td><td>4</td><td>6</td><td>0</td><td>18</td><td>23</td><td>25</td><td>8</td><td>10</td><td>4.00%</td><td>4</td><td>309</td><td>10.29</td><td>0</td><td>0</td><td>0</td><td>0</td><td>4</td><td>0</td><td>0</td><td>0</td><td>0</td><td>12</td></tr>
<tr><td><a href="PlayerReport.php?Player=9">Boruvka Banananak (R) (MOR)</a></td><td>X</td><td></td><td>30</td><td>1</td><td>0</td><td><b>1</b></td><td>-5</td><td>14</td><td>0</td><td>9</td><td>31</td><td>31</td><td>8</td><td>20</td><td>3.23%</td><td>7</td><td>366</td><td>12.20</td><td>0</td><td>0</td><td>0</td><td>0</td><td>5</td><td>0</td><td>0</td><td>0</td><td>0</td><td>18</td></tr>
<tr><td><a href="PlayerReport.php?Player=57">Daniel Garland (R) (MOR)</a></td><td>X</td><td></td><td>30</td><td>1</td><td>0</td><td><b>1</b></td><td>-3</td><td>4</td><td>0</td><td>8</td><td>16</td><td>24</td><td>7</td><td>17</td><td>4.17%</td><td>6</td><td>232</td><td>7.72</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td></tr>
<tr><td><a href="PlayerReport.php?Player=71">Ruslan Zaporozhets (R) (BOH)</a></td><td>X</td><td></td><td>30</td><td>1</td><td>0</td><td><b>1</b></td><td>0</td><td>0</td><td>0</td><td>19</td><td>22</td><td>15</td><td>7</td><td>12</td><td>6.67%</td><td>7</td><td>234</td><td>7.78</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td></tr>
<tr><td><a href="PlayerReport.php?Player=3">Andrej Doskocil (R) (MOR)</a></td><td></td><td>X</td><td>30</td><td>0</td><td>1</td><td><b>1</b></td><td>2</td><td>6</td><td>0</td><td>23</td><td>25</td><td>16</td><td>6</td><td>12</td><td>0.00%</td><td>10</td><td>374</td><td>12.47</td><td>0</td><td>0</td><td>0</td><td>0</td><td>1</td><td>0</td><td>0</td><td>0</td><td>0</td><td>7</td></tr>
<tr><td><a href="PlayerReport.php?Player=8">Bernik Vrzala (R) (BOH)</a></td><td></td><td>X</td><td>30</td><td>0</td><td>1</td><td><b>1</b></td><td>-2</td><td>8</td><td>0</td><td>39</td><td>16</td><td>16</td><td>4</td><td>8</td><td>0.00%</td><td>9</td><td>391</td><td>13.02</td><td>0</td><td>0</td><td>0</td><td>0</td><td>2</td><td>0</td><td>0</td><td>0</td><td>0</td><td>33</td></tr>
<tr><td><a href="PlayerReport.php?Player=11">Cameron Urbowicz (R) (BOH)</a></td><td>X</td><td></td><td>30</td><td>0</td><td>1</td><td><b>1</b></td><td>-1</td><td>14</td><td>0</td><td>22</td><td>16</td><td>35</td><td>6</td><td>18</td><td>0.00%</td><td>7</td><td>361</td><td>12.04</td><td>0</td><td>0</td><td>0</td><td>0</td><td>4</td><td>0</td><td>0</td><td>0</td><td>0</td><td>26</td></tr>
<tr><td><a href="PlayerReport.php?Player=17">Filip Zadina (R) (KLD)</a></td><td>X</td><td></td><td>30</td><td>0</td><td>1</td><td><b>1</b></td><td>2</td><td>6</td><td>0</td><td>30</td><td>38</td><td>33</td><td>7</td><td>14</td><td>0.00%</td><td>5</td><td>405</td><td>13.50</td><td>0</td><td>0</td><td>0</td><td>0</td><td>3</td><td>0</td><td>0</td><td>0</td><td>0</td><td>9</td></tr>
<tr><td><a href="PlayerReport.php?Player=26">Matej Elias (R) (SBE)</a></td><td></td><td>X</td><td>30</td><td>0</td><td>1</td><td><b>1</b></td><td>-2</td><td>14</td><td>0</td><td>14</td><td>37</td><td>16</td><td>14</td><td>4</td><td>0.00%</td><td>27</td><td>598</td><td>19.92</td><td>0</td><td>1</td><td>1</td><td>4</td><td>71</td><td>0</td><td>0</td><td>0</td><td>1</td><td>50</td></tr>
<tr><td><a href="PlayerReport.php?Player=30">Noctis Caelum (R) (KLD)</a></td><td></td><td>X</td><td>30</td><td>0</td><td>1</td><td><b>1</b></td><td>1</td><td>12</td><td>0</td><td>39</td><td>30</td><td>30</td><td>16</td><td>11</td><td>0.00%</td><td>29</td><td>571</td><td>19.04</td><td>0</td><td>0</td><td>0</td><td>3</td><td>61</td><td>0</td><td>0</td><td>0</td><td>0</td><td>53</td></tr>
<tr><td><a href="PlayerReport.php?Player=34">Potato Chips (R) (MOR)</a></td><td>X</td><td></td><td>30</td><td>0</td><td>1</td><td><b>1</b></td><td>-3</td><td>2</td><td>0</td><td>6</td><td>18</td><td>34</td><td>11</td><td>16</td><td>0.00%</td><td>3</td><td>243</td><td>8.11</td><td>0</td><td>0</td><td>0</td><td>0</td><td>1</td><td>0</td><td>0</td><td>0</td><td>0</td><td>8</td></tr>
<tr><td><a href="PlayerReport.php?Player=43">Soren Kierkegaard (R) (BOH)</a></td><td>X</td><td></td><td>30</td><td>0</td><td>1</td><td><b>1</b></td><td>0</td><td>2</td><td>0</td><td>8</td><td>14</td><td>55</td><td>18</td><td>27</td><td>0.00%</td><td>5</td><td>237</td><td>7.92</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>3</td></tr>
<tr><td><a href="PlayerReport.php?Player=44">Tauras Karazija (R) (SBE)</a></td><td></td><td>X</td><td>30</td><td>0</td><td>1</td><td><b>1</b></td><td>-1</td><td>8</td><td>0</td><td>4</td><td>38</td><td>11</td><td>5</td><td>5</td><td>0.00%</td><td>22</td><td>385</td><td>12.84</td><td>0</td><td>0</td><td>0</td><td>0</td><td>1</td><td>0</td><td>0</td><td>0</td><td>0</td><td>24</td></tr>
<tr><td><a href="PlayerReport.php?Player=19">Jakob Hamr (R) (KLD)</a></td><td></td><td>X</td><td>30</td><td>0</td><td>0</td><td><b>0</b></td><td>-2</td><td>16</td><td>0</td><td>13</td><td>8</td><td>0</td><td>1</td><td>3</td><td>0.00%</td><td>12</td><td>285</td><td>9.51</td><td>0</td><td>0</td><td>0</td><td>0</td><td>1</td><td>0</td><td>0</td><td>0</td><td>0</td><td>25</td></tr>
<tr><td><a href="PlayerReport.php?Player=22">Josef Novotny (R) (KLD)</a></td><td>X</td><td></td><td>30</td><td>0</td><td>0</td><td><b>0</b></td><td>0</td><td>2</td><td>0</td><td>2</td><td>4</td><td>1</td><td>1</td><td>0</td><td>0.00%</td><td>0</td><td>48</td><td>1.61</td><td>0</td><td>0</td><td>0</td><td>0</td><td>2</td><td>0</td><td>0</td><td>0</td><td>0</td><td>16</td></tr>
<tr><td><a href="PlayerReport.php?Player=28">Mikas Bieksa (R) (SBE)</a></td><td></td><td>X</td><td>30</td><td>0</td><td>0</td><td><b>0</b></td><td>-1</td><td>12</td><td>0</td><td>9</td><td>31</td><td>9</td><td>2</td><td>1</td><td>0.00%</td><td>10</td><td>359</td><td>11.96</td><td>0</td><td>0</td><td>0</td><td>0</td><td>1</td><td>0</td><td>0</td><td>0</td><td>0</td><td>1</td></tr>
<tr><td><a href="PlayerReport.php?Player=51">Flash Gordon (R) (SBE)</a></td><td></td><td>X</td><td>30</td><td>0</td><td>0</td><td><b>0</b></td><td>1</td><td>0</td><td>0</td><td>3</td><td>2</td><td>0</td><td>0</td><td>0</td><td>0.00%</td><td>1</td><td>128</td><td>4.25</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>5</td></tr>
<tr><td><a href="PlayerReport.php?Player=52">Sasha Dangelchek (R) (MOR)</a></td><td>X</td><td></td><td>30</td><td>0</td><td>0</td><td><b>0</b></td><td>-3</td><td>4</td><td>0</td><td>20</td><td>9</td><td>10</td><td>2</td><td>7</td><td>0.00%</td><td>1</td><td>232</td><td>7.73</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td></tr>
<tr><td><a href="PlayerReport.php?Player=70">Simothy Drunkebird (R) (SBE)</a></td><td>X</td><td></td><td>30</td><td>0</td><td>0</td><td><b>0</b></td><td>2</td><td>4</td><td>0</td><td>15</td><td>7</td><td>0</td><td>0</td><td>1</td><td>0.00%</td><td>2</td><td>144</td><td>4.82</td><td>0</td><td>0</td><td>0</td><td>0</td><td>6</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td></tr>
</table><br /><h1 class="ProTotalPlayerStat_Player2">Pro Players Stats #2</h1><table class="basictablesorter STHSScoring_PlayersTable2"><thead><tr><th class="STHSW200">Player Name</th><th class="STHSW10">F</th><th class="STHSW10">D</th><th class="STHSW25">GW</th><th class="STHSW25">GT</th><th class="STHSW55">FO %</th><th class="STHSW25">FOT</th><th class="STHSW25">GA</th><th class="STHSW25">TA</th><th class="STHSW25">EG</th><th class="STHSW25">HT</th><th class="STHSW25">P/20</th><th class="STHSW25">PSG</th><th class="STHSW25">PSS</th><th class="STHSW25">FW</th><th class="STHSW25">FL</th><th class="STHSW25">FT</th><th class="STHSW25">GS</th><th class="STHSW25">PS</th><th class="STHSW25">WG</th><th class="STHSW25">WP</th><th class="STHSW25">S1</th><th class="STHSW25">S2</th><th class="STHSW25">S3</th></tr></thead>
<tr><td><a href="PlayerReport.php?Player=67">Ondrej Ravchitikov (R) (MOR)</a></td><td></td><td>X</td><td>3</td><td>2</td><td>0.00%</td><td>0</td><td>40</td><td>36</td><td>1</td><td>1</td><td>0.97</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>7</td><td>5</td><td>0</td><td>3</td><td>5</td><td>1</td></tr>
<tr><td><a href="PlayerReport.php?Player=55">Walter White (R) (BOH)</a></td><td></td><td>X</td><td>1</td><td>1</td><td>0.00%</td><td>0</td><td>32</td><td>26</td><td>0</td><td>0</td><td>0.84</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>3</td><td>1</td><td>4</td><td>1</td><td>2</td></tr>
<tr><td><a href="PlayerReport.php?Player=25">Marian Potoczny (R) (MOR)</a></td><td>X</td><td></td><td>1</td><td>1</td><td>44.83%</td><td>58</td><td>44</td><td>15</td><td>0</td><td>0</td><td>0.88</td><td>0</td><td>6</td><td>0</td><td>0</td><td>0</td><td>2</td><td>2</td><td>0</td><td>0</td><td>2</td><td>2</td><td>0</td></tr>
<tr><td><a href="PlayerReport.php?Player=58">Dickie Pecker (R) (BOH)</a></td><td>X</td><td></td><td>1</td><td>1</td><td>38.33%</td><td>60</td><td>33</td><td>14</td><td>1</td><td>0</td><td>0.88</td><td>1</td><td>6</td><td>0</td><td>0</td><td>0</td><td>3</td><td>13</td><td>0</td><td>0</td><td>2</td><td>2</td><td>3</td></tr>
<tr><td><a href="PlayerReport.php?Player=69">Sachimo Zoidberg (R) (MOR)</a></td><td></td><td>X</td><td>3</td><td>2</td><td>100.00%</td><td>1</td><td>18</td><td>40</td><td>1</td><td>0</td><td>0.60</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>1</td><td>6</td><td>0</td><td>3</td><td>2</td><td>2</td></tr>
<tr><td><a href="PlayerReport.php?Player=33">Piotr Czerkawski (R) (SBE)</a></td><td>X</td><td></td><td>2</td><td>1</td><td>56.21%</td><td>153</td><td>34</td><td>21</td><td>0</td><td>0</td><td>0.63</td><td>0</td><td>2</td><td>0</td><td>0</td><td>0</td><td>1</td><td>1</td><td>0</td><td>0</td><td>1</td><td>3</td><td>2</td></tr>
<tr><td><a href="PlayerReport.php?Player=42">Slappy McDoodle (R) (MOR)</a></td><td>X</td><td></td><td>2</td><td>1</td><td>52.18%</td><td>1031</td><td>15</td><td>18</td><td>0</td><td>0</td><td>0.67</td><td>2</td><td>6</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>3</td><td>3</td><td>1</td><td>1</td><td>4</td></tr>
<tr><td><a href="PlayerReport.php?Player=49">Zalleras Szlerchek (R) (SBE)</a></td><td>X</td><td></td><td>0</td><td>1</td><td>52.20%</td><td>956</td><td>43</td><td>25</td><td>0</td><td>0</td><td>0.58</td><td>2</td><td>2</td><td>0</td><td>0</td><td>0</td><td>0</td><td>6</td><td>3</td><td>0</td><td>2</td><td>1</td><td>1</td></tr>
<tr><td><a href="PlayerReport.php?Player=65">Merit Csonka (R) (KLD)</a></td><td>X</td><td></td><td>2</td><td>1</td><td>38.52%</td><td>244</td><td>43</td><td>18</td><td>1</td><td>0</td><td>0.57</td><td>1</td><td>3</td><td>0</td><td>0</td><td>0</td><td>0</td><td>1</td><td>3</td><td>0</td><td>3</td><td>4</td><td>0</td></tr>
<tr><td><a href="PlayerReport.php?Player=15">DeMaricus Smyth (R) (BOH)</a></td><td>X</td><td></td><td>1</td><td>0</td><td>54.95%</td><td>970</td><td>21</td><td>15</td><td>0</td><td>0</td><td>0.57</td><td>2</td><td>7</td><td>0</td><td>0</td><td>0</td><td>0</td><td>2</td><td>7</td><td>0</td><td>0</td><td>1</td><td>2</td></tr>
<tr><td><a href="PlayerReport.php?Player=39">Schnitinfritz Jagr (R) (KLD)</a></td><td>X</td><td></td><td>0</td><td>1</td><td>52.54%</td><td>807</td><td>30</td><td>19</td><td>0</td><td>0</td><td>0.59</td><td>0</td><td>3</td><td>0</td><td>0</td><td>0</td><td>0</td><td>2</td><td>1</td><td>0</td><td>0</td><td>0</td><td>2</td></tr>
<tr><td><a href="PlayerReport.php?Player=62">Krysztof Kowalski (R) (SBE)</a></td><td>X</td><td></td><td>4</td><td>0</td><td>49.28%</td><td>418</td><td>15</td><td>14</td><td>0</td><td>0</td><td>0.58</td><td>0</td><td>0</td><td>1</td><td>0</td><td>0</td><td>0</td><td>0</td><td>1</td><td>1</td><td>0</td><td>2</td><td>4</td></tr>
<tr><td><a href="PlayerReport.php?Player=5">Aviad Ratzon (R) (MOR)</a></td><td>X</td><td></td><td>3</td><td>0</td><td>41.94%</td><td>62</td><td>9</td><td>13</td><td>0</td><td>0</td><td>0.49</td><td>1</td><td>6</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>7</td><td>1</td><td>1</td><td>2</td><td>0</td></tr>
<tr><td><a href="PlayerReport.php?Player=68">Patrik Satan (R) (KLD)</a></td><td>X</td><td></td><td>0</td><td>0</td><td>41.67%</td><td>24</td><td>22</td><td>11</td><td>0</td><td>0</td><td>0.57</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>2</td><td>2</td><td>0</td><td>0</td><td>2</td></tr>
<tr><td><a href="PlayerReport.php?Player=73">Vratislav Zbynek (R) (SBE)</a></td><td>X</td><td></td><td>2</td><td>0</td><td>25.00%</td><td>28</td><td>22</td><td>11</td><td>0</td><td>0</td><td>0.53</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>1</td><td>6</td><td>0</td><td>0</td><td>2</td><td>2</td></tr>
<tr><td><a href="PlayerReport.php?Player=50">Zivan Zidek (R) (MOR)</a></td><td>X</td><td></td><td>1</td><td>1</td><td>44.19%</td><td>344</td><td>7</td><td>5</td><td>0</td><td>0</td><td>0.58</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>2</td><td>2</td><td>0</td><td>1</td><td>1</td></tr>
<tr><td><a href="PlayerReport.php?Player=24">Luke Thomason (R) (BOH)</a></td><td>X</td><td></td><td>1</td><td>0</td><td>46.91%</td><td>81</td><td>16</td><td>24</td><td>0</td><td>0</td><td>0.40</td><td>2</td><td>7</td><td>0</td><td>0</td><td>0</td><td>0</td><td>1</td><td>9</td><td>0</td><td>1</td><td>0</td><td>0</td></tr>
<tr><td><a href="PlayerReport.php?Player=72">Tomas Pylon (R) (KLD)</a></td><td></td><td>X</td><td>1</td><td>0</td><td>0.00%</td><td>0</td><td>33</td><td>25</td><td>0</td><td>0</td><td>0.32</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>1</td><td>2</td><td>0</td><td>0</td><td>1</td><td>1</td><td>2</td></tr>
<tr><td><a href="PlayerReport.php?Player=60">Jakub Trocheck (R) (SBE)</a></td><td></td><td>X</td><td>2</td><td>1</td><td>0.00%</td><td>0</td><td>26</td><td>22</td><td>0</td><td>0</td><td>0.31</td><td>0</td><td>2</td><td>0</td><td>0</td><td>0</td><td>2</td><td>2</td><td>0</td><td>0</td><td>0</td><td>0</td><td>2</td></tr>
<tr><td><a href="PlayerReport.php?Player=56">Cash Savage (R) (KLD)</a></td><td>X</td><td></td><td>0</td><td>1</td><td>37.50%</td><td>32</td><td>17</td><td>12</td><td>0</td><td>0</td><td>0.49</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>9</td><td>2</td><td>1</td><td>0</td><td>0</td></tr>
<tr><td><a href="PlayerReport.php?Player=64">Matej Stransky (R) (BOH)</a></td><td>X</td><td></td><td>1</td><td>1</td><td>33.33%</td><td>24</td><td>20</td><td>5</td><td>0</td><td>0</td><td>0.42</td><td>1</td><td>3</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>2</td><td>2</td><td>2</td><td>2</td><td>0</td></tr>
<tr><td><a href="PlayerReport.php?Player=53">Jakub Novak (R) (SBE)</a></td><td>X</td><td></td><td>1</td><td>0</td><td>50.00%</td><td>30</td><td>8</td><td>12</td><td>0</td><td>0</td><td>0.36</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>8</td><td>4</td><td>1</td><td>0</td><td>1</td></tr>
<tr><td><a href="PlayerReport.php?Player=2">Alexander Zajac (R) (SBE)</a></td><td>X</td><td></td><td>2</td><td>0</td><td>54.17%</td><td>48</td><td>22</td><td>9</td><td>0</td><td>0</td><td>0.38</td><td>0</td><td>1</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>2</td><td>1</td><td>1</td><td>1</td><td>1</td></tr>
<tr><td><a href="PlayerReport.php?Player=32">Pierre-Luc Laflamme (R) (BOH)</a></td><td></td><td>X</td><td>0</td><td>2</td><td>0.00%</td><td>0</td><td>21</td><td>28</td><td>0</td><td>0</td><td>0.21</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>14</td><td>6</td><td>0</td><td>1</td><td>1</td></tr>
<tr><td><a href="PlayerReport.php?Player=27">Michael Scarn (R) (KLD)</a></td><td>X</td><td></td><td>1</td><td>0</td><td>50.52%</td><td>386</td><td>14</td><td>14</td><td>0</td><td>0</td><td>0.32</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>1</td><td>3</td><td>0</td><td>0</td><td>1</td><td>0</td><td>0</td></tr>
<tr><td><a href="PlayerReport.php?Player=7">Barret McCarthy (R) (KLD)</a></td><td></td><td>X</td><td>2</td><td>0</td><td>0.00%</td><td>0</td><td>18</td><td>39</td><td>0</td><td>0</td><td>0.20</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>19</td><td>4</td><td>1</td><td>1</td><td>2</td></tr>
<tr><td><a href="PlayerReport.php?Player=61">Petr Kolesnikovs (R) (BOH)</a></td><td>X</td><td></td><td>0</td><td>2</td><td>43.33%</td><td>30</td><td>12</td><td>9</td><td>0</td><td>0</td><td>0.34</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>2</td><td>2</td><td>0</td><td>1</td><td>0</td></tr>
<tr><td><a href="PlayerReport.php?Player=46">Travis Jeziak (R) (BOH)</a></td><td>X</td><td></td><td>5</td><td>0</td><td>49.23%</td><td>390</td><td>4</td><td>10</td><td>0</td><td>0</td><td>0.29</td><td>1</td><td>2</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>6</td><td>2</td><td>2</td><td>0</td><td>0</td></tr>
<tr><td><a href="PlayerReport.php?Player=12">Charlie Schieck (R) (SBE)</a></td><td></td><td>X</td><td>2</td><td>0</td><td>100.00%</td><td>1</td><td>11</td><td>32</td><td>0</td><td>0</td><td>0.19</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>9</td><td>1</td><td>1</td><td>1</td><td>1</td></tr>
<tr><td><a href="PlayerReport.php?Player=54">Marek Vyskoc (R) (MOR)</a></td><td>X</td><td></td><td>1</td><td>0</td><td>35.00%</td><td>20</td><td>10</td><td>13</td><td>0</td><td>0</td><td>0.29</td><td>0</td><td>2</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>6</td><td>4</td><td>0</td><td>0</td><td>2</td></tr>
<tr><td><a href="PlayerReport.php?Player=10">Brady McIntyre (R) (MOR)</a></td><td></td><td>X</td><td>0</td><td>0</td><td>0.00%</td><td>0</td><td>32</td><td>26</td><td>0</td><td>0</td><td>0.23</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>17</td><td>7</td><td>1</td><td>0</td><td>0</td></tr>
<tr><td><a href="PlayerReport.php?Player=1">Alex Winters (R) (KLD)</a></td><td>X</td><td></td><td>2</td><td>0</td><td>49.09%</td><td>55</td><td>10</td><td>20</td><td>0</td><td>0</td><td>0.20</td><td>0</td><td>2</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>1</td><td>1</td><td>0</td><td>2</td><td>0</td></tr>
<tr><td><a href="PlayerReport.php?Player=16">Dionyz Vyskoc (R) (MOR)</a></td><td>X</td><td></td><td>0</td><td>1</td><td>52.17%</td><td>23</td><td>14</td><td>7</td><td>0</td><td>0</td><td>0.23</td><td>1</td><td>2</td><td>0</td><td>1</td><td>0</td><td>0</td><td>0</td><td>8</td><td>3</td><td>0</td><td>0</td><td>1</td></tr>
<tr><td><a href="PlayerReport.php?Player=38">Samee Iqbal (R) (SBE)</a></td><td></td><td>X</td><td>0</td><td>0</td><td>0.00%</td><td>0</td><td>17</td><td>16</td><td>0</td><td>0</td><td>0.20</td><td>1</td><td>1</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>8</td><td>5</td><td>0</td><td>0</td><td>0</td></tr>
<tr><td><a href="PlayerReport.php?Player=41">Shouta Aizawa (R) (KLD)</a></td><td>X</td><td></td><td>0</td><td>1</td><td>50.54%</td><td>184</td><td>7</td><td>8</td><td>0</td><td>0</td><td>0.30</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>10</td><td>8</td><td>0</td><td>0</td><td>0</td></tr>
<tr><td><a href="PlayerReport.php?Player=63">Konstantin Voloshin (R) (BOH)</a></td><td>X</td><td></td><td>1</td><td>0</td><td>41.06%</td><td>207</td><td>8</td><td>13</td><td>0</td><td>0</td><td>0.27</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>7</td><td>5</td><td>0</td><td>0</td><td>0</td></tr>
<tr><td><a href="PlayerReport.php?Player=59">Grayson St. Raegan (R) (KLD)</a></td><td>X</td><td></td><td>1</td><td>0</td><td>36.00%</td><td>25</td><td>9</td><td>11</td><td>0</td><td>0</td><td>0.19</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>8</td><td>8</td><td>1</td><td>0</td><td>0</td></tr>
<tr><td><a href="PlayerReport.php?Player=31">Petr Mikulak (R) (BOH)</a></td><td>X</td><td></td><td>0</td><td>1</td><td>26.67%</td><td>15</td><td>11</td><td>9</td><td>0</td><td>0</td><td>0.24</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>15</td><td>7</td><td>0</td><td>1</td><td>0</td></tr>
<tr><td><a href="PlayerReport.php?Player=48">Ty Justice (R) (MOR)</a></td><td></td><td>X</td><td>0</td><td>0</td><td>0.00%</td><td>0</td><td>9</td><td>25</td><td>0</td><td>0</td><td>0.13</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>23</td><td>4</td><td>0</td><td>1</td><td>1</td></tr>
<tr><td><a href="PlayerReport.php?Player=45">Tokek Takshak (R) (BOH)</a></td><td></td><td>X</td><td>0</td><td>1</td><td>0.00%</td><td>0</td><td>12</td><td>17</td><td>0</td><td>0</td><td>0.13</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>21</td><td>15</td><td>0</td><td>0</td><td>1</td></tr>
<tr><td><a href="PlayerReport.php?Player=47">Troy McClure III (R) (KLD)</a></td><td></td><td>X</td><td>0</td><td>0</td><td>0.00%</td><td>0</td><td>12</td><td>24</td><td>0</td><td>0</td><td>0.11</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>1</td><td>1</td><td>0</td><td>0</td><td>0</td><td>1</td><td>0</td></tr>
<tr><td><a href="PlayerReport.php?Player=20">Jan Zacha (R) (BOH)</a></td><td>X</td><td></td><td>0</td><td>0</td><td>49.04%</td><td>104</td><td>4</td><td>5</td><td>0</td><td>0</td><td>0.23</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>1</td><td>1</td><td>0</td><td>0</td><td>1</td></tr>
<tr><td><a href="PlayerReport.php?Player=21">Josef Kubinec (R) (SBE)</a></td><td>X</td><td></td><td>1</td><td>0</td><td>40.00%</td><td>30</td><td>10</td><td>10</td><td>0</td><td>0</td><td>0.16</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>10</td><td>2</td><td>0</td><td>1</td><td>1</td></tr>
<tr><td><a href="PlayerReport.php?Player=29">Nico Gross (R) (MOR)</a></td><td>X</td><td></td><td>0</td><td>0</td><td>57.58%</td><td>33</td><td>14</td><td>3</td><td>0</td><td>0</td><td>0.16</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>11</td><td>6</td><td>0</td><td>0</td><td>0</td></tr>
<tr><td><a href="PlayerReport.php?Player=35">Przemyslaw Brzeszczyczkiewicz (R) (SBE)</a></td><td>X</td><td></td><td>0</td><td>1</td><td>100.00%</td><td>5</td><td>9</td><td>9</td><td>0</td><td>0</td><td>0.22</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>19</td><td>6</td><td>0</td><td>0</td><td>1</td></tr>
<tr><td><a href="PlayerReport.php?Player=13">David Kastrba (R) (SBE)</a></td><td>X</td><td></td><td>0</td><td>0</td><td>71.43%</td><td>7</td><td>8</td><td>11</td><td>0</td><td>0</td><td>0.17</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>2</td><td>2</td><td>0</td><td>0</td><td>1</td></tr>
<tr><td><a href="PlayerReport.php?Player=40">Sean Stevenson Jr. (R) (BOH)</a></td><td></td><td>X</td><td>0</td><td>0</td><td>0.00%</td><td>1</td><td>13</td><td>18</td><td>0</td><td>0</td><td>0.10</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>22</td><td>22</td><td>0</td><td>0</td><td>0</td></tr>
<tr><td><a href="PlayerReport.php?Player=36">Radovan Hudec (R) (KLD)</a></td><td>X</td><td></td><td>0</td><td>0</td><td>20.00%</td><td>5</td><td>5</td><td>4</td><td>0</td><td>0</td><td>0.22</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>15</td><td>15</td><td>0</td><td>0</td><td>0</td></tr>
<tr><td><a href="PlayerReport.php?Player=37">Ravyn Tedisko (R) (KLD)</a></td><td>X</td><td></td><td>0</td><td>0</td><td>50.00%</td><td>4</td><td>1</td><td>4</td><td>0</td><td>0</td><td>0.22</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>20</td><td>15</td><td>0</td><td>0</td><td>0</td></tr>
<tr><td><a href="PlayerReport.php?Player=6">Barak Obrana (R) (MOR)</a></td><td></td><td>X</td><td>0</td><td>0</td><td>0.00%</td><td>0</td><td>12</td><td>8</td><td>0</td><td>0</td><td>0.10</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>30</td><td>17</td><td>0</td><td>0</td><td>1</td></tr>
<tr><td><a href="PlayerReport.php?Player=14">David Vent (R) (BOH)</a></td><td></td><td>X</td><td>0</td><td>0</td><td>0.00%</td><td>0</td><td>4</td><td>16</td><td>0</td><td>0</td><td>0.11</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>30</td><td>12</td><td>0</td><td>0</td><td>0</td></tr>
<tr><td><a href="PlayerReport.php?Player=23">Kornel Kasparek (R) (KLD)</a></td><td></td><td>X</td><td>0</td><td>0</td><td>0.00%</td><td>0</td><td>5</td><td>12</td><td>0</td><td>0</td><td>0.11</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>30</td><td>11</td><td>0</td><td>0</td><td>0</td></tr>
<tr><td><a href="PlayerReport.php?Player=66">Mikhail Kladno (R) (MOR)</a></td><td>X</td><td></td><td>0</td><td>0</td><td>47.49%</td><td>179</td><td>6</td><td>9</td><td>0</td><td>0</td><td>0.12</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>30</td><td>11</td><td>0</td><td>0</td><td>0</td></tr>
<tr><td><a href="PlayerReport.php?Player=4">Aron Hernadivic (R) (SBE)</a></td><td>X</td><td></td><td>0</td><td>0</td><td>69.23%</td><td>13</td><td>6</td><td>6</td><td>0</td><td>0</td><td>0.06</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>6</td><td>6</td><td>0</td><td>0</td><td>0</td></tr>
<tr><td><a href="PlayerReport.php?Player=9">Boruvka Banananak (R) (MOR)</a></td><td>X</td><td></td><td>0</td><td>0</td><td>56.00%</td><td>25</td><td>8</td><td>3</td><td>0</td><td>0</td><td>0.05</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>17</td><td>17</td><td>0</td><td>0</td><td>0</td></tr>
<tr><td><a href="PlayerReport.php?Player=57">Daniel Garland (R) (MOR)</a></td><td>X</td><td></td><td>1</td><td>0</td><td>0.00%</td><td>2</td><td>7</td><td>7</td><td>0</td><td>0</td><td>0.09</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>27</td><td>27</td><td>0</td><td>1</td><td>0</td></tr>
<tr><td><a href="PlayerReport.php?Player=71">Ruslan Zaporozhets (R) (BOH)</a></td><td>X</td><td></td><td>0</td><td>0</td><td>66.67%</td><td>3</td><td>1</td><td>4</td><td>0</td><td>0</td><td>0.09</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>5</td><td>5</td><td>0</td><td>0</td><td>0</td></tr>
<tr><td><a href="PlayerReport.php?Player=3">Andrej Doskocil (R) (MOR)</a></td><td></td><td>X</td><td>0</td><td>0</td><td>50.00%</td><td>4</td><td>7</td><td>11</td><td>0</td><td>0</td><td>0.05</td><td>0</td><td>1</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>30</td><td>17</td><td>0</td><td>0</td><td>0</td></tr>
<tr><td><a href="PlayerReport.php?Player=8">Bernik Vrzala (R) (BOH)</a></td><td></td><td>X</td><td>0</td><td>0</td><td>0.00%</td><td>0</td><td>5</td><td>9</td><td>0</td><td>0</td><td>0.05</td><td>1</td><td>1</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>30</td><td>2</td><td>0</td><td>0</td><td>0</td></tr>
<tr><td><a href="PlayerReport.php?Player=11">Cameron Urbowicz (R) (BOH)</a></td><td>X</td><td></td><td>0</td><td>0</td><td>66.67%</td><td>12</td><td>13</td><td>7</td><td>0</td><td>0</td><td>0.06</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>30</td><td>6</td><td>0</td><td>0</td><td>0</td></tr>
<tr><td><a href="PlayerReport.php?Player=17">Filip Zadina (R) (KLD)</a></td><td>X</td><td></td><td>0</td><td>0</td><td>60.00%</td><td>20</td><td>6</td><td>12</td><td>0</td><td>0</td><td>0.05</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>30</td><td>8</td><td>0</td><td>0</td><td>0</td></tr>
<tr><td><a href="PlayerReport.php?Player=26">Matej Elias (R) (SBE)</a></td><td></td><td>X</td><td>0</td><td>0</td><td>0.00%</td><td>0</td><td>4</td><td>22</td><td>0</td><td>0</td><td>0.03</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>30</td><td>7</td><td>0</td><td>0</td><td>0</td></tr>
<tr><td><a href="PlayerReport.php?Player=30">Noctis Caelum (R) (KLD)</a></td><td></td><td>X</td><td>0</td><td>0</td><td>0.00%</td><td>0</td><td>14</td><td>14</td><td>0</td><td>0</td><td>0.04</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>30</td><td>14</td><td>0</td><td>0</td><td>0</td></tr>
<tr><td><a href="PlayerReport.php?Player=34">Potato Chips (R) (MOR)</a></td><td>X</td><td></td><td>0</td><td>0</td><td>46.59%</td><td>88</td><td>16</td><td>9</td><td>0</td><td>0</td><td>0.08</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>30</td><td>27</td><td>0</td><td>0</td><td>1</td></tr>
<tr><td><a href="PlayerReport.php?Player=43">Soren Kierkegaard (R) (BOH)</a></td><td>X</td><td></td><td>0</td><td>0</td><td>25.00%</td><td>4</td><td>14</td><td>10</td><td>0</td><td>0</td><td>0.08</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>30</td><td>29</td><td>0</td><td>0</td><td>0</td></tr>
<tr><td><a href="PlayerReport.php?Player=44">Tauras Karazija (R) (SBE)</a></td><td></td><td>X</td><td>0</td><td>0</td><td>100.00%</td><td>1</td><td>2</td><td>16</td><td>0</td><td>0</td><td>0.05</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>30</td><td>27</td><td>0</td><td>0</td><td>0</td></tr>
<tr><td><a href="PlayerReport.php?Player=19">Jakob Hamr (R) (KLD)</a></td><td></td><td>X</td><td>0</td><td>0</td><td>0.00%</td><td>0</td><td>0</td><td>4</td><td>0</td><td>0</td><td>0.00</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>30</td><td>30</td><td>0</td><td>0</td><td>0</td></tr>
<tr><td><a href="PlayerReport.php?Player=22">Josef Novotny (R) (KLD)</a></td><td>X</td><td></td><td>0</td><td>0</td><td>22.22%</td><td>9</td><td>0</td><td>1</td><td>0</td><td>0</td><td>0.00</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>30</td><td>30</td><td>0</td><td>0</td><td>0</td></tr>
<tr><td><a href="PlayerReport.php?Player=28">Mikas Bieksa (R) (SBE)</a></td><td></td><td>X</td><td>0</td><td>0</td><td>0.00%</td><td>0</td><td>3</td><td>17</td><td>0</td><td>0</td><td>0.00</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>30</td><td>30</td><td>0</td><td>0</td><td>0</td></tr>
<tr><td><a href="PlayerReport.php?Player=51">Flash Gordon (R) (SBE)</a></td><td></td><td>X</td><td>0</td><td>0</td><td>0.00%</td><td>0</td><td>0</td><td>1</td><td>0</td><td>0</td><td>0.00</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>30</td><td>30</td><td>0</td><td>0</td><td>0</td></tr>
<tr><td><a href="PlayerReport.php?Player=52">Sasha Dangelchek (R) (MOR)</a></td><td>X</td><td></td><td>0</td><td>0</td><td>20.00%</td><td>5</td><td>0</td><td>4</td><td>0</td><td>0</td><td>0.00</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>30</td><td>30</td><td>0</td><td>0</td><td>0</td></tr>
<tr><td><a href="PlayerReport.php?Player=70">Simothy Drunkebird (R) (SBE)</a></td><td>X</td><td></td><td>0</td><td>0</td><td>38.46%</td><td>39</td><td>0</td><td>1</td><td>0</td><td>0</td><td>0.00</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>30</td><td>30</td><td>0</td><td>0</td><td>0</td></tr>
</table><br /><h1 class="ProTotalPlayerStat_Goaler">Pro Goaler Stats</h1><table class="basictablesorter STHSScoring_GoaliesTable"><thead><tr><th class="STHSW200">Goalie Name</th><th class="STHSW25">GP</th><th class="STHSW25">W</th><th class="STHSW25">L</th><th class="STHSW25">OTL</th><th class="STHSW50">PCT</th><th class="STHSW50">GAA</th><th class="STHSW50">MP</th><th class="STHSW25">PIM</th><th class="STHSW25">SO</th><th class="STHSW25">GA</th><th class="STHSW45">SA</th><th class="STHSW45">SAR</th><th class="STHSW25">A</th><th class="STHSW25">EG</th><th class="STHSW50">PS %</th><th class="STHSW25">PSA</th><th class="STHSW25">ST</th><th class="STHSW25">BG</th><th class="STHSW25">S1</th><th class="STHSW25">S2</th><th class="STHSW25">S3</th></tr></thead>
<tr><td><a href="GoalieReport.php?Goalie=4">Mike Verminski (R) (SBE)</a></td><td>30</td><td>18</td><td>7</td><td>5</td><td><b>0.944</b></td><td>1.65</td><td>1821</td><td>0</td><td>2</td><td>50</td><td>891</td><td>402</td><td>3</td><td>1</td><td>1.000</td><td>6</td><td>30</td><td>0</td><td>10</td><td>5</td><td>2</td></tr>
<tr><td><a href="GoalieReport.php?Goalie=1">Chris Partridge (R) (BOH)</a></td><td>30</td><td>16</td><td>11</td><td>3</td><td><b>0.936</b></td><td>1.73</td><td>1835</td><td>2</td><td>1</td><td>53</td><td>832</td><td>329</td><td>1</td><td>1</td><td>0.800</td><td>25</td><td>30</td><td>0</td><td>4</td><td>4</td><td>4</td></tr>
<tr><td><a href="GoalieReport.php?Goalie=6">Georgette Pel (R) (KLD)</a></td><td>30</td><td>10</td><td>15</td><td>5</td><td><b>0.933</b></td><td>2.00</td><td>1826</td><td>2</td><td>2</td><td>61</td><td>905</td><td>382</td><td>0</td><td>1</td><td>0.625</td><td>8</td><td>30</td><td>0</td><td>5</td><td>4</td><td>3</td></tr>
<tr><td><a href="GoalieReport.php?Goalie=7">Christoffer Bjornsson (R) (MOR)</a></td><td>30</td><td>16</td><td>6</td><td>8</td><td><b>0.932</b></td><td>1.82</td><td>1846</td><td>0</td><td>2</td><td>56</td><td>819</td><td>352</td><td>1</td><td>1</td><td>0.636</td><td>22</td><td>30</td><td>0</td><td>5</td><td>3</td><td>2</td></tr>
</table>
<?php include "Footer.php";?>
