<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en"><head>
<script src="STHSMain.js"></script>
<title>CELH - Pro Team Scoring</title>
<script src="CELH-PLF.js"></script>
<meta name="author" content="Simon Tremblay, sths.simont.info" />
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="Decription" content="Marcus Winston - STHS - Version : 3.1.9.9 - CELH-STHS.db - CELH-STHSCareerStat.db"/>
<link href="STHSMain.css" rel="stylesheet" type="text/css" />
<style>
@media screen and (max-width: 1200px) {
.STHSWarning {display:block;}
.STHSScoring_PlayersTable1 tbody td:nth-last-child(1){display:none;}
.STHSScoring_PlayersTable1 thead th:nth-last-child(1){display:none;}
.STHSScoring_PlayersTable1 tbody td:nth-last-child(2){display:none;}
.STHSScoring_PlayersTable1 thead th:nth-last-child(2){display:none;}
.STHSScoring_PlayersTable1 tbody td:nth-last-child(3){display:none;}
.STHSScoring_PlayersTable1 thead th:nth-last-child(3){display:none;}
}
@media screen and (max-width: 1060px) {
.STHSScoring_PlayersTable1 tbody td:nth-last-child(6){display:none;}
.STHSScoring_PlayersTable1 thead th:nth-last-child(6){display:none;}
.STHSScoring_PlayersTable1 tbody td:nth-last-child(7){display:none;}
.STHSScoring_PlayersTable1 thead th:nth-last-child(7){display:none;}
.STHSScoring_PlayersTable1 tbody td:nth-last-child(8){display:none;}
.STHSScoring_PlayersTable1 thead th:nth-last-child(8){display:none;}
.STHSScoring_PlayersTable2 tbody td:nth-last-child(1){display:none;}
.STHSScoring_PlayersTable2 thead th:nth-last-child(1){display:none;}
.STHSScoring_PlayersTable2 tbody td:nth-last-child(2){display:none;}
.STHSScoring_PlayersTable2 thead th:nth-last-child(2){display:none;}
.STHSScoring_PlayersTable2 tbody td:nth-last-child(3){display:none;}
.STHSScoring_PlayersTable2 thead th:nth-last-child(3){display:none;}
.STHSScoring_GoaliesTable tbody td:nth-last-child(1){display:none;}
.STHSScoring_GoaliesTable thead th:nth-last-child(1){display:none;}
.STHSScoring_GoaliesTable tbody td:nth-last-child(2){display:none;}
.STHSScoring_GoaliesTable thead th:nth-last-child(2){display:none;}
.STHSScoring_GoaliesTable tbody td:nth-last-child(3){display:none;}
.STHSScoring_GoaliesTable thead th:nth-last-child(3){display:none;}
}
@media screen and (max-width: 960px) {
.STHSW10 {display:none;}
.STHSScoring_PlayersTable1 tbody td:nth-child(2){display:none;}
.STHSScoring_PlayersTable1 thead th:nth-child(2){display:none;}
.STHSScoring_PlayersTable1 tbody td:nth-child(3){display:none;}
.STHSScoring_PlayersTable1 thead th:nth-child(3){display:none;}
.STHSScoring_PlayersTable2 tbody td:nth-child(2){display:none;}
.STHSScoring_PlayersTable2 thead th:nth-child(2){display:none;}
.STHSScoring_PlayersTable2 tbody td:nth-child(3){display:none;}
.STHSScoring_PlayersTable2 thead th:nth-child(3){display:none;}
}
@media screen and (max-width: 890px) {
.STHSW10 {display:none;}
.STHSScoring_PlayersTable1 tbody td:nth-child(12){display:none;}
.STHSScoring_PlayersTable1 thead th:nth-child(12){display:none;}
.STHSScoring_PlayersTable1 tbody td:nth-child(14){display:none;}
.STHSScoring_PlayersTable1 thead th:nth-child(14){display:none;}
.STHSScoring_PlayersTable1 tbody td:nth-child(15){display:none;}
.STHSScoring_PlayersTable1 thead th:nth-child(15){display:none;}
.STHSScoring_GoaliesTable tbody td:nth-last-child(8){display:none;}
.STHSScoring_GoaliesTable thead th:nth-last-child(8){display:none;}
}</style>
<link href="CELH-PLF.css" rel="stylesheet" type="text/css" />
<?php If (file_exists("STHSMain-CSSOverwrite.css") == True){echo "<link href=\"STHSMain-CSSOverwrite.css\" rel=\"stylesheet\" type=\"text/css\" />";}?>
<?php $LeagueName = (string)"";
$DatabaseFile = (string)"CELH-STHS.db";
$LangOverwrite = (boolean)FALSE;
$CareerStatDatabaseFile = (string)"CELH-STHSCareerStat.db";
$lang = (string)"en"; /* The $lang option must be either "en" or "fr" */
if(isset($_GET['Lang'])){$lang  = filter_var($_GET['Lang'], FILTER_SANITIZE_STRING, FILTER_FLAG_STRIP_LOW || FILTER_FLAG_STRIP_HIGH);$LangOverwrite=TRUE;}  /* Allow Users Language Overwrite */
If ($lang == "fr"){include 'LanguageFR.php';}else{include 'LanguageEN.php';}
$db = new SQLite3($DatabaseFile);
$Active = 1; /* Show Webpage Top Menu */
include "Menu.php";?>
<script>$(function(){$("table").basictablesorter()});</script>
<div class="STHSTopLink"><a id="STHSRosterTop"></a> <a href="#HCBlackEaglesSilesia">HC Black Eagles Silesia</a> | <a href="#HCEaglesMoravia">HC Eagles Moravia</a> | <a href="#HCLionsBohemia">HC Lions Bohemia</a> | <a href="#HCLynxKladno">HC Lynx Kladno</a> | <a href="javascript:STHS_JS_CloseAll('');">Close All Team View</a> | <a href="javascript:STHS_JS_OpenAll('');">Open All Team View</a>
</div>
<h1 class="TeamScoringPro_SBE"><a id="HCBlackEaglesSilesia">HC Black Eagles Silesia</a></h1>
<div class="STHSTeamLink">
[ <a href="CELH-PLF-ProTeamRoster.php#HCBlackEaglesSilesia">Pro Team Roster</a> ]
[ <a href="CELH-PLF-ProTeamScoring.php#HCBlackEaglesSilesia">Pro Team Scoring</a> ]
[ <a href="CELH-PLF-TeamFinance.php#HCBlackEaglesSilesia">Team Finance</a> ]
[ <a href="CELH-PLF-ProTeamPlayersInfo.php#HCBlackEaglesSilesia">Pro Team PlayersInfo</a> ]
[ <a href="CELH-PLF-ProTeamLines.php#HCBlackEaglesSilesia">Pro Team Lines</a> ]
[ <a href="CELH-PLF-TeamProspects.php#HCBlackEaglesSilesia">Team Prospects</a> ]
[ <a href="CELH-PLF-ProTeamSchedule.php#HCBlackEaglesSilesia">Pro Team Schedule</a> ]
[ <a href="CELH-PLF-ProTeamStats.php#HCBlackEaglesSilesia">Pro Team Stats</a> ]
[ <a href="CELH-PLF-ProTeamStatsVS.php#HCBlackEaglesSilesia">Pro Team Stats VS</a> ]
[ <a href="CELH-PLF-TeamInjurySuspension.php#HCBlackEaglesSilesia">Team Injury Suspension</a> ]
[ <a href="CELH-PLF-TeamHistory.php#HCBlackEaglesSilesia">Team History</a> ]
[ <a href="CELH-PLF-TeamRecords.php#HCBlackEaglesSilesia">Team Records</a> ]
 [ <a href="#STHSRosterTop"><b>Page Top</b></a> ]
[ <a href="javascript:STHS_JS_ToggleTeam('STHS_JS_Team_HCBlackEaglesSilesia');"><b>Close / Open Team View</b></a> ]
</div><div id="STHS_JS_Team_HCBlackEaglesSilesia" style="display: block;">
<table class="basictablesorter STHSScoring_PlayersTable1"><thead><tr><th class="STHSW200">Player Name</th><th class="STHSW10">F</th><th class="STHSW10">D</th><th class="STHSW25">GP</th><th class="STHSW25">G</th><th class="STHSW25">A</th><th class="STHSW25">P</th><th class="STHSW25">+/-</th><th class="STHSW25">PIM</th><th class="STHSW25">PM5</th><th class="STHSW25">HIT</th><th class="STHSW25">HTT</th><th class="STHSW25">SHT</th><th class="STHSW25">OSB</th><th class="STHSW25">OSM</th><th class="STHSW55">SHT %</th><th class="STHSW25">SB</th><th class="STHSW35">MP</th><th class="STHSW35">AMG</th><th class="STHSW25">PPG</th><th class="STHSW25">PPA</th><th class="STHSW25">PPP</th><th class="STHSW25">PPS</th><th class="STHSW25">PPM</th><th class="STHSW25">PKG</th><th class="STHSW25">PKA</th><th class="STHSW25">PKP</th><th class="STHSW25">PKS</th><th class="STHSW25">PKM</th></tr></thead>
<tr><td><a href="PlayerReport.php?Player=60">Jakub Trocheck (R)</a></td><td></td><td>X</td><td>7</td><td>4</td><td>3</td><td><b>7</b></td><td>-3</td><td>4</td><td>0</td><td>11</td><td>22</td><td>24</td><td>19</td><td>2</td><td>16.67%</td><td>10</td><td>196</td><td>28.02</td><td>4</td><td>2</td><td>6</td><td>5</td><td>21</td><td>0</td><td>0</td><td>0</td><td>0</td><td>23</td></tr>
<tr><td><a href="PlayerReport.php?Player=33">Piotr Czerkawski (R)</a></td><td>X</td><td></td><td>7</td><td>3</td><td>3</td><td><b>6</b></td><td>-4</td><td>8</td><td>0</td><td>15</td><td>11</td><td>24</td><td>6</td><td>17</td><td>12.50%</td><td>5</td><td>182</td><td>26.03</td><td>3</td><td>3</td><td>6</td><td>8</td><td>19</td><td>0</td><td>0</td><td>0</td><td>0</td><td>18</td></tr>
<tr><td><a href="PlayerReport.php?Player=49">Zalleras Szlerchek (R)</a></td><td>X</td><td></td><td>7</td><td>0</td><td>5</td><td><b>5</b></td><td>-2</td><td>2</td><td>0</td><td>17</td><td>26</td><td>21</td><td>12</td><td>14</td><td>0.00%</td><td>5</td><td>192</td><td>27.49</td><td>0</td><td>4</td><td>4</td><td>0</td><td>18</td><td>0</td><td>0</td><td>0</td><td>0</td><td>21</td></tr>
<tr><td><a href="PlayerReport.php?Player=73">Vratislav Zbynek (R)</a></td><td>X</td><td></td><td>7</td><td>2</td><td>2</td><td><b>4</b></td><td>-1</td><td>2</td><td>0</td><td>16</td><td>7</td><td>26</td><td>12</td><td>11</td><td>7.69%</td><td>4</td><td>134</td><td>19.18</td><td>1</td><td>2</td><td>3</td><td>3</td><td>14</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td></tr>
<tr><td><a href="PlayerReport.php?Player=2">Alexander Zajac (R)</a></td><td>X</td><td></td><td>7</td><td>1</td><td>3</td><td><b>4</b></td><td>-1</td><td>2</td><td>0</td><td>6</td><td>8</td><td>13</td><td>6</td><td>9</td><td>7.69%</td><td>1</td><td>122</td><td>17.37</td><td>1</td><td>3</td><td>4</td><td>2</td><td>19</td><td>0</td><td>0</td><td>0</td><td>1</td><td>11</td></tr>
<tr><td><a href="PlayerReport.php?Player=62">Krysztof Kowalski (R)</a></td><td>X</td><td></td><td>7</td><td>1</td><td>3</td><td><b>4</b></td><td>-1</td><td>4</td><td>0</td><td>11</td><td>13</td><td>20</td><td>7</td><td>12</td><td>5.00%</td><td>4</td><td>147</td><td>20.97</td><td>1</td><td>2</td><td>3</td><td>2</td><td>14</td><td>0</td><td>0</td><td>0</td><td>1</td><td>8</td></tr>
<tr><td><a href="PlayerReport.php?Player=13">David Kastrba (R)</a></td><td>X</td><td></td><td>7</td><td>1</td><td>1</td><td><b>2</b></td><td>0</td><td>0</td><td>0</td><td>12</td><td>4</td><td>13</td><td>8</td><td>6</td><td>7.69%</td><td>3</td><td>84</td><td>12.07</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td></tr>
<tr><td><a href="PlayerReport.php?Player=26">Matej Elias (R)</a></td><td></td><td>X</td><td>7</td><td>0</td><td>2</td><td><b>2</b></td><td>-2</td><td>2</td><td>0</td><td>1</td><td>12</td><td>7</td><td>5</td><td>3</td><td>0.00%</td><td>4</td><td>140</td><td>20.05</td><td>0</td><td>1</td><td>1</td><td>1</td><td>12</td><td>0</td><td>0</td><td>0</td><td>0</td><td>12</td></tr>
<tr><td><a href="PlayerReport.php?Player=21">Josef Kubinec (R)</a></td><td>X</td><td></td><td>7</td><td>1</td><td>0</td><td><b>1</b></td><td>0</td><td>2</td><td>0</td><td>1</td><td>8</td><td>7</td><td>3</td><td>4</td><td>14.29%</td><td>1</td><td>91</td><td>12.95</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>9</td></tr>
<tr><td><a href="PlayerReport.php?Player=38">Samee Iqbal (R)</a></td><td></td><td>X</td><td>7</td><td>1</td><td>0</td><td><b>1</b></td><td>-2</td><td>2</td><td>0</td><td>5</td><td>10</td><td>7</td><td>4</td><td>3</td><td>14.29%</td><td>7</td><td>141</td><td>20.21</td><td>1</td><td>0</td><td>1</td><td>1</td><td>12</td><td>0</td><td>0</td><td>0</td><td>0</td><td>12</td></tr>
<tr><td><a href="PlayerReport.php?Player=12">Charlie Schieck (R)</a></td><td></td><td>X</td><td>7</td><td>0</td><td>1</td><td><b>1</b></td><td>-2</td><td>2</td><td>0</td><td>8</td><td>14</td><td>5</td><td>2</td><td>3</td><td>0.00%</td><td>10</td><td>177</td><td>25.34</td><td>0</td><td>1</td><td>1</td><td>1</td><td>21</td><td>0</td><td>0</td><td>0</td><td>0</td><td>22</td></tr>
<tr><td><a href="PlayerReport.php?Player=4">Aron Hernadivic (R)</a></td><td>X</td><td></td><td>7</td><td>0</td><td>0</td><td><b>0</b></td><td>-3</td><td>8</td><td>0</td><td>0</td><td>9</td><td>6</td><td>6</td><td>4</td><td>0.00%</td><td>2</td><td>73</td><td>10.42</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>3</td></tr>
<tr><td><a href="PlayerReport.php?Player=28">Mikas Bieksa (R)</a></td><td></td><td>X</td><td>7</td><td>0</td><td>0</td><td><b>0</b></td><td>0</td><td>4</td><td>0</td><td>2</td><td>5</td><td>1</td><td>0</td><td>2</td><td>0.00%</td><td>3</td><td>92</td><td>13.12</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td></tr>
<tr><td><a href="PlayerReport.php?Player=35">Przemyslaw Brzeszczyczkiewicz (R)</a></td><td>X</td><td></td><td>7</td><td>0</td><td>0</td><td><b>0</b></td><td>-3</td><td>2</td><td>0</td><td>3</td><td>9</td><td>10</td><td>4</td><td>5</td><td>0.00%</td><td>1</td><td>65</td><td>9.31</td><td>0</td><td>0</td><td>0</td><td>0</td><td>1</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td></tr>
<tr><td><a href="PlayerReport.php?Player=44">Tauras Karazija (R)</a></td><td></td><td>X</td><td>7</td><td>0</td><td>0</td><td><b>0</b></td><td>0</td><td>2</td><td>0</td><td>2</td><td>4</td><td>4</td><td>2</td><td>2</td><td>0.00%</td><td>9</td><td>94</td><td>13.44</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>3</td></tr>
<tr><td><a href="PlayerReport.php?Player=51">Flash Gordon (R)</a></td><td></td><td>X</td><td>7</td><td>0</td><td>0</td><td><b>0</b></td><td>-1</td><td>0</td><td>0</td><td>1</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0.00%</td><td>0</td><td>24</td><td>3.44</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td></tr>
<tr><td><a href="PlayerReport.php?Player=53">Jakub Novak (R)</a></td><td>X</td><td></td><td>7</td><td>0</td><td>0</td><td><b>0</b></td><td>-1</td><td>4</td><td>0</td><td>6</td><td>11</td><td>4</td><td>1</td><td>3</td><td>0.00%</td><td>5</td><td>134</td><td>19.21</td><td>0</td><td>0</td><td>0</td><td>0</td><td>14</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td></tr>
<tr><td><a href="PlayerReport.php?Player=70">Simothy Drunkebird (R)</a></td><td>X</td><td></td><td>7</td><td>0</td><td>0</td><td><b>0</b></td><td>1</td><td>0</td><td>0</td><td>2</td><td>2</td><td>0</td><td>0</td><td>0</td><td>0.00%</td><td>0</td><td>28</td><td>4.02</td><td>0</td><td>0</td><td>0</td><td>0</td><td>1</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td></tr>
</table><table class="basictablesorter STHSScoring_PlayersTable2"><thead><tr><th class="STHSW200">Player Name</th><th class="STHSW10">F</th><th class="STHSW10">D</th><th class="STHSW25">GW</th><th class="STHSW25">GT</th><th class="STHSW55">FO %</th><th class="STHSW25">FOT</th><th class="STHSW25">GA</th><th class="STHSW25">TA</th><th class="STHSW25">EG</th><th class="STHSW25">HT</th><th class="STHSW25">P/20</th><th class="STHSW25">PSG</th><th class="STHSW25">PSS</th><th class="STHSW25">FW</th><th class="STHSW25">FL</th><th class="STHSW25">FT</th><th class="STHSW25">GS</th><th class="STHSW25">PS</th><th class="STHSW25">WG</th><th class="STHSW25">WP</th><th class="STHSW25">S1</th><th class="STHSW25">S2</th><th class="STHSW25">S3</th></tr></thead>
<tr><td><a href="PlayerReport.php?Player=60">Jakub Trocheck (R)</a></td><td></td><td>X</td><td>0</td><td>1</td><td>0.00%</td><td>0</td><td>5</td><td>12</td><td>0</td><td>0</td><td>0.71</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>3</td><td>1</td><td>0</td><td>1</td><td>0</td><td>1</td></tr>
<tr><td><a href="PlayerReport.php?Player=33">Piotr Czerkawski (R)</a></td><td>X</td><td></td><td>1</td><td>1</td><td>57.50%</td><td>40</td><td>9</td><td>3</td><td>0</td><td>0</td><td>0.66</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>1</td><td>1</td><td>0</td><td>0</td><td>1</td><td>0</td><td>1</td></tr>
<tr><td><a href="PlayerReport.php?Player=49">Zalleras Szlerchek (R)</a></td><td>X</td><td></td><td>0</td><td>0</td><td>50.21%</td><td>237</td><td>8</td><td>9</td><td>0</td><td>0</td><td>0.52</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>1</td><td>7</td><td>0</td><td>0</td><td>0</td><td>0</td></tr>
<tr><td><a href="PlayerReport.php?Player=73">Vratislav Zbynek (R)</a></td><td>X</td><td></td><td>0</td><td>0</td><td>40.00%</td><td>5</td><td>5</td><td>1</td><td>0</td><td>0</td><td>0.60</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>1</td><td>3</td><td>0</td><td>0</td><td>1</td><td>0</td><td>0</td></tr>
<tr><td><a href="PlayerReport.php?Player=2">Alexander Zajac (R)</a></td><td>X</td><td></td><td>1</td><td>0</td><td>50.00%</td><td>18</td><td>4</td><td>1</td><td>0</td><td>0</td><td>0.66</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>1</td><td>2</td><td>0</td><td>0</td><td>0</td><td>0</td></tr>
<tr><td><a href="PlayerReport.php?Player=62">Krysztof Kowalski (R)</a></td><td>X</td><td></td><td>0</td><td>0</td><td>42.00%</td><td>100</td><td>1</td><td>1</td><td>0</td><td>0</td><td>0.54</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>3</td><td>2</td><td>0</td><td>0</td><td>1</td><td>0</td></tr>
<tr><td><a href="PlayerReport.php?Player=13">David Kastrba (R)</a></td><td>X</td><td></td><td>0</td><td>0</td><td>0.00%</td><td>2</td><td>7</td><td>4</td><td>0</td><td>0</td><td>0.47</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>1</td><td>2</td><td>0</td><td>0</td><td>0</td><td>0</td></tr>
<tr><td><a href="PlayerReport.php?Player=26">Matej Elias (R)</a></td><td></td><td>X</td><td>0</td><td>0</td><td>0.00%</td><td>0</td><td>2</td><td>6</td><td>0</td><td>0</td><td>0.28</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>1</td><td>7</td><td>0</td><td>0</td><td>0</td><td>0</td></tr>
<tr><td><a href="PlayerReport.php?Player=21">Josef Kubinec (R)</a></td><td>X</td><td></td><td>0</td><td>0</td><td>0.00%</td><td>3</td><td>1</td><td>3</td><td>0</td><td>0</td><td>0.22</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>1</td><td>1</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td></tr>
<tr><td><a href="PlayerReport.php?Player=38">Samee Iqbal (R)</a></td><td></td><td>X</td><td>1</td><td>0</td><td>0.00%</td><td>0</td><td>0</td><td>7</td><td>0</td><td>0</td><td>0.14</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>5</td><td>5</td><td>0</td><td>0</td><td>0</td></tr>
<tr><td><a href="PlayerReport.php?Player=12">Charlie Schieck (R)</a></td><td></td><td>X</td><td>0</td><td>0</td><td>0.00%</td><td>0</td><td>0</td><td>7</td><td>0</td><td>0</td><td>0.11</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>7</td><td>5</td><td>0</td><td>0</td><td>0</td></tr>
<tr><td><a href="PlayerReport.php?Player=4">Aron Hernadivic (R)</a></td><td>X</td><td></td><td>0</td><td>0</td><td>50.00%</td><td>2</td><td>1</td><td>1</td><td>0</td><td>0</td><td>0.00</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>7</td><td>7</td><td>0</td><td>0</td><td>0</td></tr>
<tr><td><a href="PlayerReport.php?Player=28">Mikas Bieksa (R)</a></td><td></td><td>X</td><td>0</td><td>0</td><td>0.00%</td><td>0</td><td>1</td><td>6</td><td>0</td><td>0</td><td>0.00</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>7</td><td>7</td><td>0</td><td>0</td><td>0</td></tr>
<tr><td><a href="PlayerReport.php?Player=35">Przemyslaw Brzeszczyczkiewicz (R)</a></td><td>X</td><td></td><td>0</td><td>0</td><td>100.00%</td><td>1</td><td>4</td><td>1</td><td>0</td><td>0</td><td>0.00</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>7</td><td>7</td><td>0</td><td>0</td><td>0</td></tr>
<tr><td><a href="PlayerReport.php?Player=44">Tauras Karazija (R)</a></td><td></td><td>X</td><td>0</td><td>0</td><td>0.00%</td><td>0</td><td>0</td><td>3</td><td>0</td><td>0</td><td>0.00</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>7</td><td>7</td><td>0</td><td>0</td><td>0</td></tr>
<tr><td><a href="PlayerReport.php?Player=51">Flash Gordon (R)</a></td><td></td><td>X</td><td>0</td><td>0</td><td>0.00%</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0.00</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>7</td><td>7</td><td>0</td><td>0</td><td>0</td></tr>
<tr><td><a href="PlayerReport.php?Player=53">Jakub Novak (R)</a></td><td>X</td><td></td><td>0</td><td>0</td><td>100.00%</td><td>3</td><td>3</td><td>2</td><td>0</td><td>0</td><td>0.00</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>7</td><td>7</td><td>0</td><td>0</td><td>0</td></tr>
<tr><td><a href="PlayerReport.php?Player=70">Simothy Drunkebird (R)</a></td><td>X</td><td></td><td>0</td><td>0</td><td>27.27%</td><td>11</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0.00</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>7</td><td>7</td><td>0</td><td>0</td><td>0</td></tr>
</table><table class="basictablesorter STHSScoring_GoaliesTable"><thead><tr><th class="STHSW200">Goalie Name</th><th class="STHSW25">GP</th><th class="STHSW25">W</th><th class="STHSW25">L</th><th class="STHSW25">OTL</th><th class="STHSW50">PCT</th><th class="STHSW50">GAA</th><th class="STHSW50">MP</th><th class="STHSW25">PIM</th><th class="STHSW25">SO</th><th class="STHSW25">GA</th><th class="STHSW45">SA</th><th class="STHSW45">SAR</th><th class="STHSW25">A</th><th class="STHSW25">EG</th><th class="STHSW50">PS %</th><th class="STHSW25">PSA</th><th class="STHSW25">ST</th><th class="STHSW25">BG</th><th class="STHSW25">S1</th><th class="STHSW25">S2</th><th class="STHSW25">S3</th></tr></thead>
<tr><td><a href="GoalieReport.php?Goalie=4">Mike Verminski (R)</a></td><td>7</td><td>3</td><td>2</td><td>2</td><td><b>0.936</b></td><td>1.94</td><td>432</td><td>0</td><td>0</td><td>14</td><td>219</td><td>94</td><td>1</td><td>0</td><td>0.000</td><td>0</td><td>7</td><td>0</td><td>0</td><td>2</td><td>1</td></tr>
<tbody></tbody></table></div>
<h1 class="TeamScoringPro_MOR"><a id="HCEaglesMoravia">HC Eagles Moravia</a></h1>
<div class="STHSTeamLink">
[ <a href="CELH-PLF-ProTeamRoster.php#HCEaglesMoravia">Pro Team Roster</a> ]
[ <a href="CELH-PLF-ProTeamScoring.php#HCEaglesMoravia">Pro Team Scoring</a> ]
[ <a href="CELH-PLF-TeamFinance.php#HCEaglesMoravia">Team Finance</a> ]
[ <a href="CELH-PLF-ProTeamPlayersInfo.php#HCEaglesMoravia">Pro Team PlayersInfo</a> ]
[ <a href="CELH-PLF-ProTeamLines.php#HCEaglesMoravia">Pro Team Lines</a> ]
[ <a href="CELH-PLF-TeamProspects.php#HCEaglesMoravia">Team Prospects</a> ]
[ <a href="CELH-PLF-ProTeamSchedule.php#HCEaglesMoravia">Pro Team Schedule</a> ]
[ <a href="CELH-PLF-ProTeamStats.php#HCEaglesMoravia">Pro Team Stats</a> ]
[ <a href="CELH-PLF-ProTeamStatsVS.php#HCEaglesMoravia">Pro Team Stats VS</a> ]
[ <a href="CELH-PLF-TeamInjurySuspension.php#HCEaglesMoravia">Team Injury Suspension</a> ]
[ <a href="CELH-PLF-TeamHistory.php#HCEaglesMoravia">Team History</a> ]
[ <a href="CELH-PLF-TeamRecords.php#HCEaglesMoravia">Team Records</a> ]
 [ <a href="#STHSRosterTop"><b>Page Top</b></a> ]
[ <a href="javascript:STHS_JS_ToggleTeam('STHS_JS_Team_HCEaglesMoravia');"><b>Close / Open Team View</b></a> ]
</div><div id="STHS_JS_Team_HCEaglesMoravia" style="display: block;">
<table class="basictablesorter STHSScoring_PlayersTable1"><thead><tr><th class="STHSW200">Player Name</th><th class="STHSW10">F</th><th class="STHSW10">D</th><th class="STHSW25">GP</th><th class="STHSW25">G</th><th class="STHSW25">A</th><th class="STHSW25">P</th><th class="STHSW25">+/-</th><th class="STHSW25">PIM</th><th class="STHSW25">PM5</th><th class="STHSW25">HIT</th><th class="STHSW25">HTT</th><th class="STHSW25">SHT</th><th class="STHSW25">OSB</th><th class="STHSW25">OSM</th><th class="STHSW55">SHT %</th><th class="STHSW25">SB</th><th class="STHSW35">MP</th><th class="STHSW35">AMG</th><th class="STHSW25">PPG</th><th class="STHSW25">PPA</th><th class="STHSW25">PPP</th><th class="STHSW25">PPS</th><th class="STHSW25">PPM</th><th class="STHSW25">PKG</th><th class="STHSW25">PKA</th><th class="STHSW25">PKP</th><th class="STHSW25">PKS</th><th class="STHSW25">PKM</th></tr></thead>
<tr><td><a href="PlayerReport.php?Player=67">Ondrej Ravchitikov (R)</a></td><td></td><td>X</td><td>13</td><td>3</td><td>8</td><td><b>11</b></td><td>0</td><td>2</td><td>0</td><td>14</td><td>26</td><td>60</td><td>25</td><td>40</td><td>5.00%</td><td>23</td><td>363</td><td>27.90</td><td>3</td><td>3</td><td>6</td><td>16</td><td>43</td><td>0</td><td>0</td><td>0</td><td>0</td><td>38</td></tr>
<tr><td><a href="PlayerReport.php?Player=16">Dionyz Vyskoc (R)</a></td><td>X</td><td></td><td>13</td><td>5</td><td>4</td><td><b>9</b></td><td>4</td><td>6</td><td>0</td><td>12</td><td>18</td><td>16</td><td>5</td><td>9</td><td>31.25%</td><td>4</td><td>232</td><td>17.85</td><td>1</td><td>2</td><td>3</td><td>3</td><td>30</td><td>1</td><td>0</td><td>1</td><td>1</td><td>13</td></tr>
<tr><td><a href="PlayerReport.php?Player=42">Slappy McDoodle (R)</a></td><td>X</td><td></td><td>13</td><td>4</td><td>4</td><td><b>8</b></td><td>3</td><td>8</td><td>0</td><td>20</td><td>21</td><td>35</td><td>10</td><td>19</td><td>11.43%</td><td>5</td><td>299</td><td>22.97</td><td>2</td><td>4</td><td>6</td><td>6</td><td>39</td><td>0</td><td>0</td><td>0</td><td>0</td><td>35</td></tr>
<tr><td><a href="PlayerReport.php?Player=69">Sachimo Zoidberg (R)</a></td><td></td><td>X</td><td>13</td><td>2</td><td>6</td><td><b>8</b></td><td>0</td><td>14</td><td>0</td><td>45</td><td>22</td><td>39</td><td>19</td><td>18</td><td>5.13%</td><td>20</td><td>356</td><td>27.36</td><td>0</td><td>3</td><td>3</td><td>7</td><td>43</td><td>0</td><td>0</td><td>0</td><td>0</td><td>33</td></tr>
<tr><td><a href="PlayerReport.php?Player=10">Brady McIntyre (R)</a></td><td></td><td>X</td><td>13</td><td>1</td><td>6</td><td><b>7</b></td><td>8</td><td>8</td><td>0</td><td>23</td><td>18</td><td>23</td><td>10</td><td>7</td><td>4.35%</td><td>21</td><td>276</td><td>21.20</td><td>1</td><td>1</td><td>2</td><td>4</td><td>27</td><td>0</td><td>1</td><td>1</td><td>0</td><td>27</td></tr>
<tr><td><a href="PlayerReport.php?Player=50">Zivan Zidek (R)</a></td><td>X</td><td></td><td>13</td><td>2</td><td>3</td><td><b>5</b></td><td>3</td><td>8</td><td>0</td><td>12</td><td>16</td><td>26</td><td>9</td><td>26</td><td>7.69%</td><td>1</td><td>217</td><td>16.66</td><td>1</td><td>2</td><td>3</td><td>4</td><td>30</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td></tr>
<tr><td><a href="PlayerReport.php?Player=25">Marian Potoczny (R)</a></td><td>X</td><td></td><td>13</td><td>2</td><td>2</td><td><b>4</b></td><td>3</td><td>12</td><td>0</td><td>23</td><td>16</td><td>41</td><td>10</td><td>30</td><td>4.88%</td><td>9</td><td>297</td><td>22.85</td><td>1</td><td>2</td><td>3</td><td>3</td><td>39</td><td>0</td><td>0</td><td>0</td><td>0</td><td>36</td></tr>
<tr><td><a href="PlayerReport.php?Player=54">Marek Vyskoc (R)</a></td><td>X</td><td></td><td>13</td><td>1</td><td>3</td><td><b>4</b></td><td>3</td><td>8</td><td>0</td><td>15</td><td>11</td><td>27</td><td>7</td><td>19</td><td>3.70%</td><td>7</td><td>216</td><td>16.64</td><td>0</td><td>1</td><td>1</td><td>1</td><td>30</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td></tr>
<tr><td><a href="PlayerReport.php?Player=48">Ty Justice (R)</a></td><td></td><td>X</td><td>13</td><td>2</td><td>1</td><td><b>3</b></td><td>8</td><td>2</td><td>0</td><td>22</td><td>12</td><td>20</td><td>8</td><td>3</td><td>10.00%</td><td>24</td><td>275</td><td>21.13</td><td>2</td><td>1</td><td>3</td><td>4</td><td>27</td><td>0</td><td>0</td><td>0</td><td>0</td><td>26</td></tr>
<tr><td><a href="PlayerReport.php?Player=5">Aviad Ratzon (R)</a></td><td>X</td><td></td><td>13</td><td>1</td><td>2</td><td><b>3</b></td><td>4</td><td>8</td><td>0</td><td>28</td><td>17</td><td>12</td><td>5</td><td>14</td><td>8.33%</td><td>12</td><td>283</td><td>21.78</td><td>1</td><td>1</td><td>2</td><td>2</td><td>39</td><td>0</td><td>1</td><td>1</td><td>0</td><td>22</td></tr>
<tr><td><a href="PlayerReport.php?Player=57">Daniel Garland (R)</a></td><td>X</td><td></td><td>13</td><td>1</td><td>1</td><td><b>2</b></td><td>1</td><td>6</td><td>0</td><td>5</td><td>10</td><td>18</td><td>5</td><td>8</td><td>5.56%</td><td>2</td><td>103</td><td>7.92</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td></tr>
<tr><td><a href="PlayerReport.php?Player=29">Nico Gross (R)</a></td><td>X</td><td></td><td>13</td><td>1</td><td>0</td><td><b>1</b></td><td>-2</td><td>6</td><td>0</td><td>20</td><td>9</td><td>15</td><td>2</td><td>11</td><td>6.67%</td><td>4</td><td>162</td><td>12.46</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>14</td></tr>
<tr><td><a href="PlayerReport.php?Player=52">Sasha Dangelchek (R)</a></td><td>X</td><td></td><td>13</td><td>1</td><td>0</td><td><b>1</b></td><td>1</td><td>0</td><td>0</td><td>6</td><td>4</td><td>4</td><td>1</td><td>2</td><td>25.00%</td><td>5</td><td>102</td><td>7.87</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td></tr>
<tr><td><a href="PlayerReport.php?Player=34">Potato Chips (R)</a></td><td>X</td><td></td><td>13</td><td>0</td><td>1</td><td><b>1</b></td><td>1</td><td>0</td><td>0</td><td>4</td><td>4</td><td>18</td><td>3</td><td>8</td><td>0.00%</td><td>4</td><td>108</td><td>8.28</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>3</td></tr>
<tr><td><a href="PlayerReport.php?Player=66">Mikhail Kladno (R)</a></td><td>X</td><td></td><td>13</td><td>0</td><td>1</td><td><b>1</b></td><td>-2</td><td>8</td><td>0</td><td>9</td><td>15</td><td>15</td><td>1</td><td>14</td><td>0.00%</td><td>3</td><td>148</td><td>11.40</td><td>0</td><td>0</td><td>0</td><td>0</td><td>1</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td></tr>
<tr><td><a href="PlayerReport.php?Player=3">Andrej Doskocil (R)</a></td><td></td><td>X</td><td>13</td><td>0</td><td>0</td><td><b>0</b></td><td>-2</td><td>0</td><td>0</td><td>18</td><td>10</td><td>7</td><td>3</td><td>5</td><td>0.00%</td><td>8</td><td>165</td><td>12.68</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>1</td></tr>
<tr><td><a href="PlayerReport.php?Player=6">Barak Obrana (R)</a></td><td></td><td>X</td><td>13</td><td>0</td><td>0</td><td><b>0</b></td><td>-2</td><td>2</td><td>0</td><td>9</td><td>7</td><td>12</td><td>2</td><td>1</td><td>0.00%</td><td>1</td><td>167</td><td>12.84</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>7</td></tr>
<tr><td><a href="PlayerReport.php?Player=9">Boruvka Banananak (R)</a></td><td>X</td><td></td><td>13</td><td>0</td><td>0</td><td><b>0</b></td><td>-2</td><td>6</td><td>0</td><td>13</td><td>7</td><td>12</td><td>3</td><td>7</td><td>0.00%</td><td>8</td><td>159</td><td>12.21</td><td>0</td><td>0</td><td>0</td><td>0</td><td>1</td><td>0</td><td>0</td><td>0</td><td>0</td><td>8</td></tr>
</table><table class="basictablesorter STHSScoring_PlayersTable2"><thead><tr><th class="STHSW200">Player Name</th><th class="STHSW10">F</th><th class="STHSW10">D</th><th class="STHSW25">GW</th><th class="STHSW25">GT</th><th class="STHSW55">FO %</th><th class="STHSW25">FOT</th><th class="STHSW25">GA</th><th class="STHSW25">TA</th><th class="STHSW25">EG</th><th class="STHSW25">HT</th><th class="STHSW25">P/20</th><th class="STHSW25">PSG</th><th class="STHSW25">PSS</th><th class="STHSW25">FW</th><th class="STHSW25">FL</th><th class="STHSW25">FT</th><th class="STHSW25">GS</th><th class="STHSW25">PS</th><th class="STHSW25">WG</th><th class="STHSW25">WP</th><th class="STHSW25">S1</th><th class="STHSW25">S2</th><th class="STHSW25">S3</th></tr></thead>
<tr><td><a href="PlayerReport.php?Player=67">Ondrej Ravchitikov (R)</a></td><td></td><td>X</td><td>0</td><td>0</td><td>0.00%</td><td>0</td><td>23</td><td>18</td><td>0</td><td>0</td><td>0.61</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>1</td><td>7</td><td>0</td><td>0</td><td>0</td><td>0</td><td>3</td></tr>
<tr><td><a href="PlayerReport.php?Player=16">Dionyz Vyskoc (R)</a></td><td>X</td><td></td><td>3</td><td>0</td><td>50.00%</td><td>8</td><td>3</td><td>7</td><td>0</td><td>0</td><td>0.78</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>1</td><td>4</td><td>0</td><td>0</td><td>1</td><td>0</td></tr>
<tr><td><a href="PlayerReport.php?Player=42">Slappy McDoodle (R)</a></td><td>X</td><td></td><td>3</td><td>0</td><td>52.38%</td><td>441</td><td>8</td><td>4</td><td>0</td><td>0</td><td>0.54</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>4</td><td>1</td><td>0</td><td>1</td><td>1</td><td>1</td></tr>
<tr><td><a href="PlayerReport.php?Player=69">Sachimo Zoidberg (R)</a></td><td></td><td>X</td><td>1</td><td>0</td><td>0.00%</td><td>0</td><td>11</td><td>16</td><td>0</td><td>0</td><td>0.45</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>3</td><td>1</td><td>0</td><td>2</td><td>1</td></tr>
<tr><td><a href="PlayerReport.php?Player=10">Brady McIntyre (R)</a></td><td></td><td>X</td><td>0</td><td>0</td><td>0.00%</td><td>0</td><td>8</td><td>13</td><td>0</td><td>0</td><td>0.51</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>1</td><td>1</td><td>0</td><td>0</td><td>0</td><td>1</td><td>0</td></tr>
<tr><td><a href="PlayerReport.php?Player=50">Zivan Zidek (R)</a></td><td>X</td><td></td><td>0</td><td>0</td><td>48.41%</td><td>157</td><td>13</td><td>3</td><td>0</td><td>0</td><td>0.46</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>1</td><td>6</td><td>0</td><td>0</td><td>0</td><td>2</td></tr>
<tr><td><a href="PlayerReport.php?Player=25">Marian Potoczny (R)</a></td><td>X</td><td></td><td>1</td><td>0</td><td>72.73%</td><td>22</td><td>7</td><td>7</td><td>0</td><td>0</td><td>0.27</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>1</td><td>1</td><td>0</td><td>0</td><td>1</td><td>0</td><td>0</td></tr>
<tr><td><a href="PlayerReport.php?Player=54">Marek Vyskoc (R)</a></td><td>X</td><td></td><td>0</td><td>0</td><td>31.25%</td><td>16</td><td>7</td><td>1</td><td>0</td><td>0</td><td>0.37</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>2</td><td>2</td><td>0</td><td>1</td><td>0</td></tr>
<tr><td><a href="PlayerReport.php?Player=48">Ty Justice (R)</a></td><td></td><td>X</td><td>0</td><td>0</td><td>0.00%</td><td>0</td><td>6</td><td>12</td><td>0</td><td>0</td><td>0.22</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>10</td><td>6</td><td>0</td><td>0</td><td>0</td></tr>
<tr><td><a href="PlayerReport.php?Player=5">Aviad Ratzon (R)</a></td><td>X</td><td></td><td>0</td><td>0</td><td>40.74%</td><td>27</td><td>2</td><td>4</td><td>0</td><td>0</td><td>0.21</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>4</td><td>1</td><td>0</td><td>0</td><td>1</td></tr>
<tr><td><a href="PlayerReport.php?Player=57">Daniel Garland (R)</a></td><td>X</td><td></td><td>0</td><td>1</td><td>75.00%</td><td>4</td><td>3</td><td>5</td><td>0</td><td>0</td><td>0.39</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>7</td><td>6</td><td>0</td><td>0</td><td>0</td></tr>
<tr><td><a href="PlayerReport.php?Player=29">Nico Gross (R)</a></td><td>X</td><td></td><td>0</td><td>0</td><td>37.50%</td><td>16</td><td>4</td><td>1</td><td>0</td><td>0</td><td>0.12</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>6</td><td>6</td><td>1</td><td>0</td><td>0</td></tr>
<tr><td><a href="PlayerReport.php?Player=52">Sasha Dangelchek (R)</a></td><td>X</td><td></td><td>0</td><td>0</td><td>33.33%</td><td>3</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0.20</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>6</td><td>6</td><td>0</td><td>1</td><td>0</td></tr>
<tr><td><a href="PlayerReport.php?Player=34">Potato Chips (R)</a></td><td>X</td><td></td><td>0</td><td>0</td><td>47.06%</td><td>34</td><td>4</td><td>4</td><td>0</td><td>0</td><td>0.19</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>13</td><td>6</td><td>0</td><td>0</td><td>0</td></tr>
<tr><td><a href="PlayerReport.php?Player=66">Mikhail Kladno (R)</a></td><td>X</td><td></td><td>0</td><td>0</td><td>44.44%</td><td>72</td><td>4</td><td>5</td><td>0</td><td>0</td><td>0.13</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>13</td><td>6</td><td>0</td><td>0</td><td>0</td></tr>
<tr><td><a href="PlayerReport.php?Player=3">Andrej Doskocil (R)</a></td><td></td><td>X</td><td>0</td><td>0</td><td>0.00%</td><td>0</td><td>3</td><td>1</td><td>0</td><td>0</td><td>0.00</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>13</td><td>13</td><td>0</td><td>0</td><td>0</td></tr>
<tr><td><a href="PlayerReport.php?Player=6">Barak Obrana (R)</a></td><td></td><td>X</td><td>0</td><td>0</td><td>0.00%</td><td>0</td><td>1</td><td>4</td><td>0</td><td>0</td><td>0.00</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>13</td><td>13</td><td>0</td><td>0</td><td>0</td></tr>
<tr><td><a href="PlayerReport.php?Player=9">Boruvka Banananak (R)</a></td><td>X</td><td></td><td>0</td><td>0</td><td>66.67%</td><td>3</td><td>4</td><td>1</td><td>0</td><td>0</td><td>0.00</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>13</td><td>13</td><td>0</td><td>0</td><td>0</td></tr>
</table><table class="basictablesorter STHSScoring_GoaliesTable"><thead><tr><th class="STHSW200">Goalie Name</th><th class="STHSW25">GP</th><th class="STHSW25">W</th><th class="STHSW25">L</th><th class="STHSW25">OTL</th><th class="STHSW50">PCT</th><th class="STHSW50">GAA</th><th class="STHSW50">MP</th><th class="STHSW25">PIM</th><th class="STHSW25">SO</th><th class="STHSW25">GA</th><th class="STHSW45">SA</th><th class="STHSW45">SAR</th><th class="STHSW25">A</th><th class="STHSW25">EG</th><th class="STHSW50">PS %</th><th class="STHSW25">PSA</th><th class="STHSW25">ST</th><th class="STHSW25">BG</th><th class="STHSW25">S1</th><th class="STHSW25">S2</th><th class="STHSW25">S3</th></tr></thead>
<tr><td><a href="GoalieReport.php?Goalie=7">Christoffer Bjornsson (R)</a></td><td>13</td><td>8</td><td>5</td><td>0</td><td><b>0.926</b></td><td>2.11</td><td>798</td><td>0</td><td>3</td><td>28</td><td>377</td><td>164</td><td>3</td><td>0</td><td>0.000</td><td>0</td><td>13</td><td>0</td><td>5</td><td>1</td><td>0</td></tr>
<tbody></tbody></table></div>
<h1 class="TeamScoringPro_BOH"><a id="HCLionsBohemia">HC Lions Bohemia</a></h1>
<div class="STHSTeamLink">
[ <a href="CELH-PLF-ProTeamRoster.php#HCLionsBohemia">Pro Team Roster</a> ]
[ <a href="CELH-PLF-ProTeamScoring.php#HCLionsBohemia">Pro Team Scoring</a> ]
[ <a href="CELH-PLF-TeamFinance.php#HCLionsBohemia">Team Finance</a> ]
[ <a href="CELH-PLF-ProTeamPlayersInfo.php#HCLionsBohemia">Pro Team PlayersInfo</a> ]
[ <a href="CELH-PLF-ProTeamLines.php#HCLionsBohemia">Pro Team Lines</a> ]
[ <a href="CELH-PLF-TeamProspects.php#HCLionsBohemia">Team Prospects</a> ]
[ <a href="CELH-PLF-ProTeamSchedule.php#HCLionsBohemia">Pro Team Schedule</a> ]
[ <a href="CELH-PLF-ProTeamStats.php#HCLionsBohemia">Pro Team Stats</a> ]
[ <a href="CELH-PLF-ProTeamStatsVS.php#HCLionsBohemia">Pro Team Stats VS</a> ]
[ <a href="CELH-PLF-TeamInjurySuspension.php#HCLionsBohemia">Team Injury Suspension</a> ]
[ <a href="CELH-PLF-TeamHistory.php#HCLionsBohemia">Team History</a> ]
[ <a href="CELH-PLF-TeamRecords.php#HCLionsBohemia">Team Records</a> ]
 [ <a href="#STHSRosterTop"><b>Page Top</b></a> ]
[ <a href="javascript:STHS_JS_ToggleTeam('STHS_JS_Team_HCLionsBohemia');"><b>Close / Open Team View</b></a> ]
</div><div id="STHS_JS_Team_HCLionsBohemia" style="display: block;">
<table class="basictablesorter STHSScoring_PlayersTable1"><thead><tr><th class="STHSW200">Player Name</th><th class="STHSW10">F</th><th class="STHSW10">D</th><th class="STHSW25">GP</th><th class="STHSW25">G</th><th class="STHSW25">A</th><th class="STHSW25">P</th><th class="STHSW25">+/-</th><th class="STHSW25">PIM</th><th class="STHSW25">PM5</th><th class="STHSW25">HIT</th><th class="STHSW25">HTT</th><th class="STHSW25">SHT</th><th class="STHSW25">OSB</th><th class="STHSW25">OSM</th><th class="STHSW55">SHT %</th><th class="STHSW25">SB</th><th class="STHSW35">MP</th><th class="STHSW35">AMG</th><th class="STHSW25">PPG</th><th class="STHSW25">PPA</th><th class="STHSW25">PPP</th><th class="STHSW25">PPS</th><th class="STHSW25">PPM</th><th class="STHSW25">PKG</th><th class="STHSW25">PKA</th><th class="STHSW25">PKP</th><th class="STHSW25">PKS</th><th class="STHSW25">PKM</th></tr></thead>
<tr><td><a href="PlayerReport.php?Player=58">Dickie Pecker (R)</a></td><td>X</td><td></td><td>10</td><td>3</td><td>11</td><td><b>14</b></td><td>-3</td><td>0</td><td>0</td><td>10</td><td>19</td><td>45</td><td>9</td><td>24</td><td>6.67%</td><td>4</td><td>212</td><td>21.18</td><td>3</td><td>9</td><td>12</td><td>10</td><td>34</td><td>0</td><td>0</td><td>0</td><td>1</td><td>15</td></tr>
<tr><td><a href="PlayerReport.php?Player=55">Walter White (R)</a></td><td></td><td>X</td><td>10</td><td>6</td><td>7</td><td><b>13</b></td><td>-1</td><td>10</td><td>0</td><td>28</td><td>18</td><td>47</td><td>16</td><td>13</td><td>12.77%</td><td>13</td><td>283</td><td>28.26</td><td>4</td><td>6</td><td>10</td><td>12</td><td>38</td><td>0</td><td>0</td><td>0</td><td>0</td><td>32</td></tr>
<tr><td><a href="PlayerReport.php?Player=15">DeMaricus Smyth (R)</a></td><td>X</td><td></td><td>10</td><td>2</td><td>7</td><td><b>9</b></td><td>-4</td><td>8</td><td>0</td><td>21</td><td>28</td><td>19</td><td>8</td><td>13</td><td>10.53%</td><td>6</td><td>228</td><td>22.79</td><td>2</td><td>7</td><td>9</td><td>4</td><td>34</td><td>0</td><td>0</td><td>0</td><td>0</td><td>29</td></tr>
<tr><td><a href="PlayerReport.php?Player=64">Matej Stransky (R)</a></td><td>X</td><td></td><td>10</td><td>5</td><td>2</td><td><b>7</b></td><td>2</td><td>6</td><td>0</td><td>15</td><td>16</td><td>33</td><td>5</td><td>19</td><td>15.15%</td><td>0</td><td>176</td><td>17.60</td><td>3</td><td>1</td><td>4</td><td>4</td><td>27</td><td>0</td><td>0</td><td>0</td><td>0</td><td>14</td></tr>
<tr><td><a href="PlayerReport.php?Player=24">Luke Thomason (R)</a></td><td>X</td><td></td><td>10</td><td>2</td><td>4</td><td><b>6</b></td><td>-4</td><td>0</td><td>0</td><td>14</td><td>17</td><td>16</td><td>2</td><td>13</td><td>12.50%</td><td>7</td><td>230</td><td>23.03</td><td>2</td><td>4</td><td>6</td><td>3</td><td>33</td><td>0</td><td>0</td><td>0</td><td>1</td><td>33</td></tr>
<tr><td><a href="PlayerReport.php?Player=61">Petr Kolesnikovs (R)</a></td><td>X</td><td></td><td>10</td><td>2</td><td>2</td><td><b>4</b></td><td>1</td><td>4</td><td>0</td><td>9</td><td>14</td><td>14</td><td>12</td><td>11</td><td>14.29%</td><td>4</td><td>157</td><td>15.67</td><td>1</td><td>1</td><td>2</td><td>3</td><td>26</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td></tr>
<tr><td><a href="PlayerReport.php?Player=63">Konstantin Voloshin (R)</a></td><td>X</td><td></td><td>10</td><td>2</td><td>2</td><td><b>4</b></td><td>2</td><td>2</td><td>0</td><td>5</td><td>8</td><td>21</td><td>6</td><td>10</td><td>9.52%</td><td>4</td><td>121</td><td>12.13</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>1</td><td>11</td></tr>
<tr><td><a href="PlayerReport.php?Player=46">Travis Jeziak (R)</a></td><td>X</td><td></td><td>10</td><td>1</td><td>3</td><td><b>4</b></td><td>1</td><td>4</td><td>0</td><td>22</td><td>13</td><td>9</td><td>4</td><td>9</td><td>11.11%</td><td>0</td><td>157</td><td>15.68</td><td>1</td><td>1</td><td>2</td><td>1</td><td>26</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td></tr>
<tr><td><a href="PlayerReport.php?Player=31">Petr Mikulak (R)</a></td><td>X</td><td></td><td>10</td><td>0</td><td>3</td><td><b>3</b></td><td>2</td><td>2</td><td>0</td><td>11</td><td>5</td><td>11</td><td>6</td><td>12</td><td>0.00%</td><td>0</td><td>114</td><td>11.35</td><td>0</td><td>0</td><td>0</td><td>1</td><td>2</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td></tr>
<tr><td><a href="PlayerReport.php?Player=11">Cameron Urbowicz (R)</a></td><td>X</td><td></td><td>10</td><td>1</td><td>1</td><td><b>2</b></td><td>2</td><td>0</td><td>0</td><td>4</td><td>2</td><td>18</td><td>4</td><td>9</td><td>5.56%</td><td>3</td><td>122</td><td>12.19</td><td>0</td><td>0</td><td>0</td><td>0</td><td>3</td><td>0</td><td>0</td><td>0</td><td>1</td><td>9</td></tr>
<tr><td><a href="PlayerReport.php?Player=32">Pierre-Luc Laflamme (R)</a></td><td></td><td>X</td><td>10</td><td>0</td><td>2</td><td><b>2</b></td><td>0</td><td>18</td><td>0</td><td>23</td><td>25</td><td>11</td><td>6</td><td>7</td><td>0.00%</td><td>16</td><td>280</td><td>27.96</td><td>0</td><td>0</td><td>0</td><td>1</td><td>37</td><td>0</td><td>0</td><td>0</td><td>0</td><td>28</td></tr>
<tr><td><a href="PlayerReport.php?Player=45">Tokek Takshak (R)</a></td><td></td><td>X</td><td>10</td><td>1</td><td>0</td><td><b>1</b></td><td>0</td><td>8</td><td>0</td><td>6</td><td>17</td><td>14</td><td>3</td><td>3</td><td>7.14%</td><td>6</td><td>200</td><td>19.97</td><td>1</td><td>0</td><td>1</td><td>2</td><td>25</td><td>0</td><td>0</td><td>0</td><td>0</td><td>21</td></tr>
<tr><td><a href="PlayerReport.php?Player=8">Bernik Vrzala (R)</a></td><td></td><td>X</td><td>10</td><td>0</td><td>0</td><td><b>0</b></td><td>1</td><td>0</td><td>0</td><td>10</td><td>3</td><td>2</td><td>3</td><td>0</td><td>0.00%</td><td>3</td><td>136</td><td>13.59</td><td>0</td><td>0</td><td>0</td><td>0</td><td>1</td><td>0</td><td>0</td><td>0</td><td>0</td><td>17</td></tr>
<tr><td><a href="PlayerReport.php?Player=14">David Vent (R)</a></td><td></td><td>X</td><td>10</td><td>0</td><td>0</td><td><b>0</b></td><td>2</td><td>2</td><td>0</td><td>6</td><td>5</td><td>1</td><td>2</td><td>2</td><td>0.00%</td><td>6</td><td>121</td><td>12.15</td><td>0</td><td>0</td><td>0</td><td>0</td><td>1</td><td>0</td><td>0</td><td>0</td><td>0</td><td>1</td></tr>
<tr><td><a href="PlayerReport.php?Player=20">Jan Zacha (R)</a></td><td>X</td><td></td><td>10</td><td>0</td><td>0</td><td><b>0</b></td><td>0</td><td>6</td><td>0</td><td>3</td><td>8</td><td>10</td><td>1</td><td>7</td><td>0.00%</td><td>3</td><td>86</td><td>8.58</td><td>0</td><td>0</td><td>0</td><td>0</td><td>1</td><td>0</td><td>0</td><td>0</td><td>0</td><td>5</td></tr>
<tr><td><a href="PlayerReport.php?Player=40">Sean Stevenson Jr. (R)</a></td><td></td><td>X</td><td>10</td><td>0</td><td>0</td><td><b>0</b></td><td>-1</td><td>0</td><td>0</td><td>13</td><td>16</td><td>11</td><td>3</td><td>5</td><td>0.00%</td><td>11</td><td>200</td><td>20.04</td><td>0</td><td>0</td><td>0</td><td>1</td><td>25</td><td>0</td><td>0</td><td>0</td><td>0</td><td>21</td></tr>
<tr><td><a href="PlayerReport.php?Player=43">Soren Kierkegaard (R)</a></td><td>X</td><td></td><td>10</td><td>0</td><td>0</td><td><b>0</b></td><td>0</td><td>0</td><td>0</td><td>1</td><td>7</td><td>15</td><td>6</td><td>3</td><td>0.00%</td><td>1</td><td>78</td><td>7.76</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>1</td></tr>
<tr><td><a href="PlayerReport.php?Player=71">Ruslan Zaporozhets (R)</a></td><td>X</td><td></td><td>10</td><td>0</td><td>0</td><td><b>0</b></td><td>0</td><td>0</td><td>0</td><td>4</td><td>5</td><td>4</td><td>1</td><td>2</td><td>0.00%</td><td>1</td><td>77</td><td>7.69</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td></tr>
</table><table class="basictablesorter STHSScoring_PlayersTable2"><thead><tr><th class="STHSW200">Player Name</th><th class="STHSW10">F</th><th class="STHSW10">D</th><th class="STHSW25">GW</th><th class="STHSW25">GT</th><th class="STHSW55">FO %</th><th class="STHSW25">FOT</th><th class="STHSW25">GA</th><th class="STHSW25">TA</th><th class="STHSW25">EG</th><th class="STHSW25">HT</th><th class="STHSW25">P/20</th><th class="STHSW25">PSG</th><th class="STHSW25">PSS</th><th class="STHSW25">FW</th><th class="STHSW25">FL</th><th class="STHSW25">FT</th><th class="STHSW25">GS</th><th class="STHSW25">PS</th><th class="STHSW25">WG</th><th class="STHSW25">WP</th><th class="STHSW25">S1</th><th class="STHSW25">S2</th><th class="STHSW25">S3</th></tr></thead>
<tr><td><a href="PlayerReport.php?Player=58">Dickie Pecker (R)</a></td><td>X</td><td></td><td>1</td><td>0</td><td>50.00%</td><td>24</td><td>11</td><td>3</td><td>0</td><td>0</td><td>1.32</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>5</td><td>4</td><td>0</td><td>2</td><td>1</td></tr>
<tr><td><a href="PlayerReport.php?Player=55">Walter White (R)</a></td><td></td><td>X</td><td>1</td><td>1</td><td>0.00%</td><td>0</td><td>16</td><td>12</td><td>1</td><td>0</td><td>0.92</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>1</td><td>1</td><td>0</td><td>0</td><td>3</td><td>1</td><td>0</td></tr>
<tr><td><a href="PlayerReport.php?Player=15">DeMaricus Smyth (R)</a></td><td>X</td><td></td><td>1</td><td>1</td><td>53.73%</td><td>322</td><td>6</td><td>1</td><td>0</td><td>0</td><td>0.79</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>1</td><td>6</td><td>0</td><td>0</td><td>0</td><td>0</td></tr>
<tr><td><a href="PlayerReport.php?Player=64">Matej Stransky (R)</a></td><td>X</td><td></td><td>2</td><td>0</td><td>0.00%</td><td>2</td><td>6</td><td>1</td><td>0</td><td>0</td><td>0.80</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>1</td><td>1</td><td>0</td><td>0</td><td>0</td><td>2</td><td>0</td></tr>
<tr><td><a href="PlayerReport.php?Player=24">Luke Thomason (R)</a></td><td>X</td><td></td><td>1</td><td>0</td><td>43.48%</td><td>23</td><td>6</td><td>3</td><td>0</td><td>0</td><td>0.52</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>1</td><td>7</td><td>0</td><td>0</td><td>1</td><td>0</td></tr>
<tr><td><a href="PlayerReport.php?Player=61">Petr Kolesnikovs (R)</a></td><td>X</td><td></td><td>0</td><td>1</td><td>50.00%</td><td>10</td><td>4</td><td>4</td><td>0</td><td>0</td><td>0.51</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>1</td><td>5</td><td>0</td><td>0</td><td>0</td><td>0</td></tr>
<tr><td><a href="PlayerReport.php?Player=63">Konstantin Voloshin (R)</a></td><td>X</td><td></td><td>0</td><td>0</td><td>44.62%</td><td>65</td><td>12</td><td>6</td><td>0</td><td>0</td><td>0.66</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>1</td><td>1</td><td>0</td><td>0</td><td>1</td></tr>
<tr><td><a href="PlayerReport.php?Player=46">Travis Jeziak (R)</a></td><td>X</td><td></td><td>0</td><td>0</td><td>53.57%</td><td>112</td><td>4</td><td>3</td><td>0</td><td>0</td><td>0.51</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>5</td><td>2</td><td>0</td><td>0</td><td>0</td></tr>
<tr><td><a href="PlayerReport.php?Player=31">Petr Mikulak (R)</a></td><td>X</td><td></td><td>0</td><td>0</td><td>40.00%</td><td>5</td><td>5</td><td>2</td><td>0</td><td>0</td><td>0.53</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>10</td><td>1</td><td>0</td><td>0</td><td>0</td></tr>
<tr><td><a href="PlayerReport.php?Player=11">Cameron Urbowicz (R)</a></td><td>X</td><td></td><td>0</td><td>0</td><td>50.00%</td><td>2</td><td>4</td><td>0</td><td>0</td><td>0</td><td>0.33</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>5</td><td>1</td><td>0</td><td>0</td><td>0</td></tr>
<tr><td><a href="PlayerReport.php?Player=32">Pierre-Luc Laflamme (R)</a></td><td></td><td>X</td><td>0</td><td>0</td><td>0.00%</td><td>0</td><td>7</td><td>6</td><td>0</td><td>0</td><td>0.14</td><td>0</td><td>1</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>10</td><td>6</td><td>0</td><td>0</td><td>0</td></tr>
<tr><td><a href="PlayerReport.php?Player=45">Tokek Takshak (R)</a></td><td></td><td>X</td><td>0</td><td>0</td><td>0.00%</td><td>0</td><td>0</td><td>7</td><td>0</td><td>0</td><td>0.10</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>8</td><td>8</td><td>0</td><td>0</td><td>1</td></tr>
<tr><td><a href="PlayerReport.php?Player=8">Bernik Vrzala (R)</a></td><td></td><td>X</td><td>0</td><td>0</td><td>0.00%</td><td>0</td><td>0</td><td>2</td><td>0</td><td>0</td><td>0.00</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>10</td><td>10</td><td>0</td><td>0</td><td>0</td></tr>
<tr><td><a href="PlayerReport.php?Player=14">David Vent (R)</a></td><td></td><td>X</td><td>0</td><td>0</td><td>0.00%</td><td>0</td><td>1</td><td>6</td><td>0</td><td>0</td><td>0.00</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>10</td><td>10</td><td>0</td><td>0</td><td>0</td></tr>
<tr><td><a href="PlayerReport.php?Player=20">Jan Zacha (R)</a></td><td>X</td><td></td><td>0</td><td>0</td><td>54.29%</td><td>35</td><td>2</td><td>2</td><td>0</td><td>0</td><td>0.00</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>10</td><td>10</td><td>0</td><td>0</td><td>0</td></tr>
<tr><td><a href="PlayerReport.php?Player=40">Sean Stevenson Jr. (R)</a></td><td></td><td>X</td><td>0</td><td>0</td><td>0.00%</td><td>0</td><td>2</td><td>7</td><td>0</td><td>0</td><td>0.00</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>10</td><td>10</td><td>0</td><td>0</td><td>0</td></tr>
<tr><td><a href="PlayerReport.php?Player=43">Soren Kierkegaard (R)</a></td><td>X</td><td></td><td>0</td><td>0</td><td>50.00%</td><td>2</td><td>5</td><td>1</td><td>0</td><td>0</td><td>0.00</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>10</td><td>10</td><td>0</td><td>0</td><td>0</td></tr>
<tr><td><a href="PlayerReport.php?Player=71">Ruslan Zaporozhets (R)</a></td><td>X</td><td></td><td>0</td><td>0</td><td>33.33%</td><td>3</td><td>0</td><td>1</td><td>0</td><td>0</td><td>0.00</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>10</td><td>10</td><td>0</td><td>0</td><td>0</td></tr>
</table><table class="basictablesorter STHSScoring_GoaliesTable"><thead><tr><th class="STHSW200">Goalie Name</th><th class="STHSW25">GP</th><th class="STHSW25">W</th><th class="STHSW25">L</th><th class="STHSW25">OTL</th><th class="STHSW50">PCT</th><th class="STHSW50">GAA</th><th class="STHSW50">MP</th><th class="STHSW25">PIM</th><th class="STHSW25">SO</th><th class="STHSW25">GA</th><th class="STHSW45">SA</th><th class="STHSW45">SAR</th><th class="STHSW25">A</th><th class="STHSW25">EG</th><th class="STHSW50">PS %</th><th class="STHSW25">PSA</th><th class="STHSW25">ST</th><th class="STHSW25">BG</th><th class="STHSW25">S1</th><th class="STHSW25">S2</th><th class="STHSW25">S3</th></tr></thead>
<tr><td><a href="GoalieReport.php?Goalie=1">Chris Partridge (R)</a></td><td>10</td><td>6</td><td>2</td><td>2</td><td><b>0.951</b></td><td>1.38</td><td>607</td><td>2</td><td>2</td><td>14</td><td>285</td><td>120</td><td>1</td><td>0</td><td>0.000</td><td>0</td><td>10</td><td>0</td><td>3</td><td>0</td><td>2</td></tr>
<tbody></tbody></table></div>
<h1 class="TeamScoringPro_KLD"><a id="HCLynxKladno">HC Lynx Kladno</a></h1>
<div class="STHSTeamLink">
[ <a href="CELH-PLF-ProTeamRoster.php#HCLynxKladno">Pro Team Roster</a> ]
[ <a href="CELH-PLF-ProTeamScoring.php#HCLynxKladno">Pro Team Scoring</a> ]
[ <a href="CELH-PLF-TeamFinance.php#HCLynxKladno">Team Finance</a> ]
[ <a href="CELH-PLF-ProTeamPlayersInfo.php#HCLynxKladno">Pro Team PlayersInfo</a> ]
[ <a href="CELH-PLF-ProTeamLines.php#HCLynxKladno">Pro Team Lines</a> ]
[ <a href="CELH-PLF-TeamProspects.php#HCLynxKladno">Team Prospects</a> ]
[ <a href="CELH-PLF-ProTeamSchedule.php#HCLynxKladno">Pro Team Schedule</a> ]
[ <a href="CELH-PLF-ProTeamStats.php#HCLynxKladno">Pro Team Stats</a> ]
[ <a href="CELH-PLF-ProTeamStatsVS.php#HCLynxKladno">Pro Team Stats VS</a> ]
[ <a href="CELH-PLF-TeamInjurySuspension.php#HCLynxKladno">Team Injury Suspension</a> ]
[ <a href="CELH-PLF-TeamHistory.php#HCLynxKladno">Team History</a> ]
[ <a href="CELH-PLF-TeamRecords.php#HCLynxKladno">Team Records</a> ]
 [ <a href="#STHSRosterTop"><b>Page Top</b></a> ]
[ <a href="javascript:STHS_JS_ToggleTeam('STHS_JS_Team_HCLynxKladno');"><b>Close / Open Team View</b></a> ]
</div><div id="STHS_JS_Team_HCLynxKladno" style="display: block;">
<table class="basictablesorter STHSScoring_PlayersTable1"><thead><tr><th class="STHSW200">Player Name</th><th class="STHSW10">F</th><th class="STHSW10">D</th><th class="STHSW25">GP</th><th class="STHSW25">G</th><th class="STHSW25">A</th><th class="STHSW25">P</th><th class="STHSW25">+/-</th><th class="STHSW25">PIM</th><th class="STHSW25">PM5</th><th class="STHSW25">HIT</th><th class="STHSW25">HTT</th><th class="STHSW25">SHT</th><th class="STHSW25">OSB</th><th class="STHSW25">OSM</th><th class="STHSW55">SHT %</th><th class="STHSW25">SB</th><th class="STHSW35">MP</th><th class="STHSW35">AMG</th><th class="STHSW25">PPG</th><th class="STHSW25">PPA</th><th class="STHSW25">PPP</th><th class="STHSW25">PPS</th><th class="STHSW25">PPM</th><th class="STHSW25">PKG</th><th class="STHSW25">PKA</th><th class="STHSW25">PKP</th><th class="STHSW25">PKS</th><th class="STHSW25">PKM</th></tr></thead>
<tr><td><a href="PlayerReport.php?Player=56">Cash Savage (R)</a></td><td>X</td><td></td><td>4</td><td>1</td><td>0</td><td><b>1</b></td><td>-2</td><td>2</td><td>0</td><td>9</td><td>1</td><td>7</td><td>3</td><td>1</td><td>14.29%</td><td>0</td><td>70</td><td>17.40</td><td>0</td><td>0</td><td>0</td><td>0</td><td>12</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td></tr>
<tr><td><a href="PlayerReport.php?Player=65">Merit Csonka (R)</a></td><td>X</td><td></td><td>4</td><td>1</td><td>0</td><td><b>1</b></td><td>1</td><td>4</td><td>0</td><td>9</td><td>10</td><td>25</td><td>5</td><td>12</td><td>4.00%</td><td>1</td><td>99</td><td>24.83</td><td>0</td><td>0</td><td>0</td><td>1</td><td>13</td><td>0</td><td>0</td><td>0</td><td>2</td><td>15</td></tr>
<tr><td><a href="PlayerReport.php?Player=39">Schnitinfritz Jagr (R)</a></td><td>X</td><td></td><td>4</td><td>0</td><td>1</td><td><b>1</b></td><td>1</td><td>2</td><td>0</td><td>4</td><td>2</td><td>13</td><td>6</td><td>3</td><td>0.00%</td><td>2</td><td>87</td><td>21.68</td><td>0</td><td>0</td><td>0</td><td>1</td><td>13</td><td>0</td><td>0</td><td>0</td><td>0</td><td>16</td></tr>
<tr><td><a href="PlayerReport.php?Player=68">Patrik Satan (R)</a></td><td>X</td><td></td><td>4</td><td>0</td><td>1</td><td><b>1</b></td><td>-2</td><td>2</td><td>0</td><td>3</td><td>1</td><td>9</td><td>2</td><td>5</td><td>0.00%</td><td>2</td><td>70</td><td>17.41</td><td>0</td><td>0</td><td>0</td><td>1</td><td>12</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td></tr>
<tr><td><a href="PlayerReport.php?Player=1">Alex Winters (R)</a></td><td>X</td><td></td><td>4</td><td>0</td><td>0</td><td><b>0</b></td><td>1</td><td>2</td><td>0</td><td>1</td><td>7</td><td>4</td><td>2</td><td>3</td><td>0.00%</td><td>1</td><td>80</td><td>20.10</td><td>0</td><td>0</td><td>0</td><td>0</td><td>13</td><td>0</td><td>0</td><td>0</td><td>1</td><td>11</td></tr>
<tr><td><a href="PlayerReport.php?Player=7">Barret McCarthy (R)</a></td><td></td><td>X</td><td>4</td><td>0</td><td>0</td><td><b>0</b></td><td>-2</td><td>4</td><td>0</td><td>11</td><td>7</td><td>5</td><td>1</td><td>0</td><td>0.00%</td><td>4</td><td>100</td><td>24.95</td><td>0</td><td>0</td><td>0</td><td>0</td><td>10</td><td>0</td><td>0</td><td>0</td><td>0</td><td>10</td></tr>
<tr><td><a href="PlayerReport.php?Player=17">Filip Zadina (R)</a></td><td>X</td><td></td><td>4</td><td>0</td><td>0</td><td><b>0</b></td><td>0</td><td>6</td><td>0</td><td>4</td><td>4</td><td>2</td><td>4</td><td>0</td><td>0.00%</td><td>0</td><td>49</td><td>12.33</td><td>0</td><td>0</td><td>0</td><td>0</td><td>1</td><td>0</td><td>0</td><td>0</td><td>0</td><td>2</td></tr>
<tr><td><a href="PlayerReport.php?Player=19">Jakob Hamr (R)</a></td><td></td><td>X</td><td>4</td><td>0</td><td>0</td><td><b>0</b></td><td>0</td><td>4</td><td>0</td><td>3</td><td>2</td><td>0</td><td>0</td><td>0</td><td>0.00%</td><td>1</td><td>35</td><td>8.77</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>4</td></tr>
<tr><td><a href="PlayerReport.php?Player=22">Josef Novotny (R)</a></td><td>X</td><td></td><td>4</td><td>0</td><td>0</td><td><b>0</b></td><td>0</td><td>0</td><td>0</td><td>1</td><td>1</td><td>0</td><td>0</td><td>0</td><td>0.00%</td><td>1</td><td>8</td><td>1.93</td><td>0</td><td>0</td><td>0</td><td>0</td><td>1</td><td>0</td><td>0</td><td>0</td><td>0</td><td>3</td></tr>
<tr><td><a href="PlayerReport.php?Player=23">Kornel Kasparek (R)</a></td><td></td><td>X</td><td>4</td><td>0</td><td>0</td><td><b>0</b></td><td>-2</td><td>0</td><td>0</td><td>10</td><td>4</td><td>1</td><td>0</td><td>1</td><td>0.00%</td><td>2</td><td>44</td><td>11.11</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td></tr>
<tr><td><a href="PlayerReport.php?Player=27">Michael Scarn (R)</a></td><td>X</td><td></td><td>4</td><td>0</td><td>0</td><td><b>0</b></td><td>-2</td><td>4</td><td>0</td><td>8</td><td>5</td><td>3</td><td>1</td><td>0</td><td>0.00%</td><td>2</td><td>76</td><td>18.95</td><td>0</td><td>0</td><td>0</td><td>0</td><td>12</td><td>0</td><td>0</td><td>0</td><td>0</td><td>6</td></tr>
<tr><td><a href="PlayerReport.php?Player=30">Noctis Caelum (R)</a></td><td></td><td>X</td><td>4</td><td>0</td><td>0</td><td><b>0</b></td><td>0</td><td>2</td><td>0</td><td>5</td><td>5</td><td>1</td><td>0</td><td>2</td><td>0.00%</td><td>3</td><td>75</td><td>18.75</td><td>0</td><td>0</td><td>0</td><td>0</td><td>10</td><td>0</td><td>0</td><td>0</td><td>0</td><td>10</td></tr>
<tr><td><a href="PlayerReport.php?Player=36">Radovan Hudec (R)</a></td><td>X</td><td></td><td>4</td><td>0</td><td>0</td><td><b>0</b></td><td>0</td><td>4</td><td>0</td><td>1</td><td>3</td><td>1</td><td>0</td><td>1</td><td>0.00%</td><td>0</td><td>23</td><td>5.73</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td></tr>
<tr><td><a href="PlayerReport.php?Player=37">Ravyn Tedisko (R)</a></td><td>X</td><td></td><td>4</td><td>0</td><td>0</td><td><b>0</b></td><td>0</td><td>0</td><td>0</td><td>1</td><td>3</td><td>3</td><td>0</td><td>0</td><td>0.00%</td><td>0</td><td>23</td><td>5.69</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td></tr>
<tr><td><a href="PlayerReport.php?Player=41">Shouta Aizawa (R)</a></td><td>X</td><td></td><td>4</td><td>0</td><td>0</td><td><b>0</b></td><td>0</td><td>0</td><td>0</td><td>5</td><td>3</td><td>3</td><td>4</td><td>3</td><td>0.00%</td><td>1</td><td>48</td><td>12.04</td><td>0</td><td>0</td><td>0</td><td>0</td><td>1</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td></tr>
<tr><td><a href="PlayerReport.php?Player=47">Troy McClure III (R)</a></td><td></td><td>X</td><td>4</td><td>0</td><td>0</td><td><b>0</b></td><td>1</td><td>0</td><td>0</td><td>14</td><td>7</td><td>7</td><td>0</td><td>2</td><td>0.00%</td><td>7</td><td>106</td><td>26.38</td><td>0</td><td>0</td><td>0</td><td>0</td><td>16</td><td>0</td><td>0</td><td>0</td><td>1</td><td>18</td></tr>
<tr><td><a href="PlayerReport.php?Player=59">Grayson St. Raegan (R)</a></td><td>X</td><td></td><td>4</td><td>0</td><td>0</td><td><b>0</b></td><td>0</td><td>2</td><td>0</td><td>7</td><td>6</td><td>8</td><td>3</td><td>7</td><td>0.00%</td><td>0</td><td>57</td><td>14.20</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>8</td></tr>
<tr><td><a href="PlayerReport.php?Player=72">Tomas Pylon (R)</a></td><td></td><td>X</td><td>4</td><td>0</td><td>0</td><td><b>0</b></td><td>1</td><td>2</td><td>0</td><td>7</td><td>10</td><td>12</td><td>3</td><td>3</td><td>0.00%</td><td>6</td><td>120</td><td>30.06</td><td>0</td><td>0</td><td>0</td><td>1</td><td>16</td><td>0</td><td>0</td><td>0</td><td>0</td><td>18</td></tr>
</table><table class="basictablesorter STHSScoring_PlayersTable2"><thead><tr><th class="STHSW200">Player Name</th><th class="STHSW10">F</th><th class="STHSW10">D</th><th class="STHSW25">GW</th><th class="STHSW25">GT</th><th class="STHSW55">FO %</th><th class="STHSW25">FOT</th><th class="STHSW25">GA</th><th class="STHSW25">TA</th><th class="STHSW25">EG</th><th class="STHSW25">HT</th><th class="STHSW25">P/20</th><th class="STHSW25">PSG</th><th class="STHSW25">PSS</th><th class="STHSW25">FW</th><th class="STHSW25">FL</th><th class="STHSW25">FT</th><th class="STHSW25">GS</th><th class="STHSW25">PS</th><th class="STHSW25">WG</th><th class="STHSW25">WP</th><th class="STHSW25">S1</th><th class="STHSW25">S2</th><th class="STHSW25">S3</th></tr></thead>
<tr><td><a href="PlayerReport.php?Player=56">Cash Savage (R)</a></td><td>X</td><td></td><td>0</td><td>0</td><td>33.33%</td><td>3</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0.29</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>1</td><td>1</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td></tr>
<tr><td><a href="PlayerReport.php?Player=65">Merit Csonka (R)</a></td><td>X</td><td></td><td>0</td><td>0</td><td>13.79%</td><td>29</td><td>4</td><td>4</td><td>0</td><td>0</td><td>0.20</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>1</td><td>1</td><td>0</td><td>0</td><td>0</td></tr>
<tr><td><a href="PlayerReport.php?Player=39">Schnitinfritz Jagr (R)</a></td><td>X</td><td></td><td>0</td><td>0</td><td>55.88%</td><td>102</td><td>4</td><td>2</td><td>0</td><td>0</td><td>0.23</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>4</td><td>1</td><td>0</td><td>0</td><td>0</td></tr>
<tr><td><a href="PlayerReport.php?Player=68">Patrik Satan (R)</a></td><td>X</td><td></td><td>0</td><td>0</td><td>80.00%</td><td>5</td><td>1</td><td>2</td><td>0</td><td>0</td><td>0.29</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>1</td><td>4</td><td>0</td><td>0</td><td>0</td><td>0</td></tr>
<tr><td><a href="PlayerReport.php?Player=1">Alex Winters (R)</a></td><td>X</td><td></td><td>0</td><td>0</td><td>66.67%</td><td>6</td><td>1</td><td>3</td><td>0</td><td>0</td><td>0.00</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>4</td><td>4</td><td>0</td><td>0</td><td>0</td></tr>
<tr><td><a href="PlayerReport.php?Player=7">Barret McCarthy (R)</a></td><td></td><td>X</td><td>0</td><td>0</td><td>0.00%</td><td>0</td><td>1</td><td>6</td><td>0</td><td>0</td><td>0.00</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>4</td><td>4</td><td>0</td><td>0</td><td>0</td></tr>
<tr><td><a href="PlayerReport.php?Player=17">Filip Zadina (R)</a></td><td>X</td><td></td><td>0</td><td>0</td><td>0.00%</td><td>1</td><td>1</td><td>1</td><td>0</td><td>0</td><td>0.00</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>4</td><td>4</td><td>0</td><td>0</td><td>0</td></tr>
<tr><td><a href="PlayerReport.php?Player=19">Jakob Hamr (R)</a></td><td></td><td>X</td><td>0</td><td>0</td><td>0.00%</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0.00</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>4</td><td>4</td><td>0</td><td>0</td><td>0</td></tr>
<tr><td><a href="PlayerReport.php?Player=22">Josef Novotny (R)</a></td><td>X</td><td></td><td>0</td><td>0</td><td>20.00%</td><td>5</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0.00</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>4</td><td>4</td><td>0</td><td>0</td><td>0</td></tr>
<tr><td><a href="PlayerReport.php?Player=23">Kornel Kasparek (R)</a></td><td></td><td>X</td><td>0</td><td>0</td><td>0.00%</td><td>0</td><td>0</td><td>1</td><td>0</td><td>0</td><td>0.00</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>4</td><td>4</td><td>0</td><td>0</td><td>0</td></tr>
<tr><td><a href="PlayerReport.php?Player=27">Michael Scarn (R)</a></td><td>X</td><td></td><td>0</td><td>0</td><td>51.28%</td><td>39</td><td>2</td><td>4</td><td>0</td><td>0</td><td>0.00</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>4</td><td>4</td><td>0</td><td>0</td><td>0</td></tr>
<tr><td><a href="PlayerReport.php?Player=30">Noctis Caelum (R)</a></td><td></td><td>X</td><td>0</td><td>0</td><td>0.00%</td><td>0</td><td>4</td><td>6</td><td>0</td><td>0</td><td>0.00</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>4</td><td>4</td><td>0</td><td>0</td><td>0</td></tr>
<tr><td><a href="PlayerReport.php?Player=36">Radovan Hudec (R)</a></td><td>X</td><td></td><td>0</td><td>0</td><td>0.00%</td><td>0</td><td>0</td><td>1</td><td>0</td><td>0</td><td>0.00</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>4</td><td>4</td><td>0</td><td>0</td><td>0</td></tr>
<tr><td><a href="PlayerReport.php?Player=37">Ravyn Tedisko (R)</a></td><td>X</td><td></td><td>0</td><td>0</td><td>0.00%</td><td>1</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0.00</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>4</td><td>4</td><td>0</td><td>0</td><td>0</td></tr>
<tr><td><a href="PlayerReport.php?Player=41">Shouta Aizawa (R)</a></td><td>X</td><td></td><td>0</td><td>0</td><td>47.83%</td><td>23</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0.00</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>4</td><td>4</td><td>0</td><td>0</td><td>0</td></tr>
<tr><td><a href="PlayerReport.php?Player=47">Troy McClure III (R)</a></td><td></td><td>X</td><td>0</td><td>0</td><td>0.00%</td><td>0</td><td>1</td><td>0</td><td>0</td><td>0</td><td>0.00</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>4</td><td>4</td><td>0</td><td>0</td><td>0</td></tr>
<tr><td><a href="PlayerReport.php?Player=59">Grayson St. Raegan (R)</a></td><td>X</td><td></td><td>0</td><td>0</td><td>60.00%</td><td>10</td><td>0</td><td>1</td><td>0</td><td>0</td><td>0.00</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>4</td><td>4</td><td>0</td><td>0</td><td>0</td></tr>
<tr><td><a href="PlayerReport.php?Player=72">Tomas Pylon (R)</a></td><td></td><td>X</td><td>0</td><td>0</td><td>0.00%</td><td>0</td><td>4</td><td>5</td><td>0</td><td>0</td><td>0.00</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>4</td><td>4</td><td>0</td><td>0</td><td>0</td></tr>
</table><table class="basictablesorter STHSScoring_GoaliesTable"><thead><tr><th class="STHSW200">Goalie Name</th><th class="STHSW25">GP</th><th class="STHSW25">W</th><th class="STHSW25">L</th><th class="STHSW25">OTL</th><th class="STHSW50">PCT</th><th class="STHSW50">GAA</th><th class="STHSW50">MP</th><th class="STHSW25">PIM</th><th class="STHSW25">SO</th><th class="STHSW25">GA</th><th class="STHSW45">SA</th><th class="STHSW45">SAR</th><th class="STHSW25">A</th><th class="STHSW25">EG</th><th class="STHSW50">PS %</th><th class="STHSW25">PSA</th><th class="STHSW25">ST</th><th class="STHSW25">BG</th><th class="STHSW25">S1</th><th class="STHSW25">S2</th><th class="STHSW25">S3</th></tr></thead>
<tr><td><a href="GoalieReport.php?Goalie=6">Georgette Pel (R)</a></td><td>4</td><td>0</td><td>4</td><td>0</td><td><b>0.913</b></td><td>2.51</td><td>239</td><td>0</td><td>0</td><td>10</td><td>115</td><td>50</td><td>0</td><td>1</td><td>0.000</td><td>0</td><td>4</td><td>0</td><td>0</td><td>0</td><td>1</td></tr>
<tbody></tbody></table></div>
<?php include "Footer.php";?>
